-- salacommander configuration template.
--
-- This is the full reference for `salacommander.conf.lua`, the file
-- salacommander runs once at startup (see salacommander/config.zig
-- `load`). Copy it to one of:
--
--   $GLYPHWIRE_CONFIG_DIR/salacommander.conf.lua
--   $XDG_CONFIG_HOME/glyphwire/salacommander.conf.lua
--   ~/.config/glyphwire/salacommander.conf.lua          (the usual location)
--
-- Every key is listed below at its built-in default, with every line
-- commented out -- so copying this file verbatim changes nothing.
-- Uncomment and edit only the keys you want to override.
--
-- Syntax: a plain Lua script (standard libraries open). Assign a single
-- global table named `config`. Unknown keys are ignored; a key of the
-- wrong type is logged and the default stands. Any parse error is logged
-- and whatever parsed before it is kept. `-L`/`-S`/`-a` on the command
-- line beat `view`/`show_hidden` here.

-- config = {
--
--     ---- Listing ---------------------------------------------------
--
--     -- "small": one row per entry with a one-row icon.
--     -- "large": two rows per entry, a tall icon, and the permissions
--     -- and owner under the name. Ctrl+1 / Ctrl+2 switch per pane.
--     view = "small",
--
--     -- Show dotfiles. Ctrl+H toggles it per pane.
--     show_hidden = false,
--
--     -- Icon height caps in pixels (8..128), as in ls.conf.lua. The
--     -- rows a view has still bound them: one cell tall in "small",
--     -- two in "large".
--     small_icon_px = 16,
--     large_icon_px = 32,
--
--     ---- Opening files ---------------------------------------------
--
--     -- What runs when a file is activated (Enter, double-click),
--     -- keyed by its extension: lowercased, with or without a leading
--     -- dot ("md", ".md" and "*.md" are the same key). The value is a
--     -- command, split on spaces -- there is no shell here, so no
--     -- pipes, no quoting, no globs. The word {sel} becomes the file's
--     -- absolute path; a command without one gets the path appended.
--     --
--     -- A glyphwire client named here runs in this session: it opens
--     -- its own context over salacommander, takes the keyboard, and
--     -- salacommander comes back (and rereads both panes) when it
--     -- exits. Anything with no entry goes to xdg-open, detached, as
--     -- every file did before this table.
--     --
--     -- These entries apply over the built-in defaults below; set one
--     -- to false to put that extension back on xdg-open.
--     open_actions = {
--         md   = "gwmd {sel}",
--         cbz  = "gw-read {sel}",
--         cbr  = "gw-read {sel}",
--         png  = "gw-view {sel}",
--         jpg  = "gw-view {sel}",
--         jpeg = "gw-view {sel}",
--         -- ["pdf"] = "zathura",   -- {sel} appended
--         -- ["png"] = false,       -- back to xdg-open
--     },
--
--     ---- Keys ------------------------------------------------------
--
--     -- Rebind actions by name. Each entry maps a chord to an action,
--     -- or to false to unbind that chord. Entries apply over the
--     -- built-in bindings, so list only what you change.
--     --
--     -- Typing a letter isn't a binding: it moves the cursor to the
--     -- first entry starting with what's been typed, refining as you
--     -- go. Backspace shortens that, Escape drops it, and anything
--     -- that moves the cursor or rereads the listing ends it. That's
--     -- why Backspace isn't bound to upToParentDir (Alt+Up is).
--     --
--     -- Chords are "mod+mod+key", case-insensitive: ctrl, alt, shift,
--     -- super; keys are glyphwire key names (up, page_down, insert,
--     -- F5, kp_add, a, one, ...) or the aliases esc, pgup, pgdn, del,
--     -- ins, bs and the digits 0-9.
--     --
--     -- Actions and their default chords:
--     --   cursorUp            up
--     --   cursorDown          down
--     --   pageUp              page_up
--     --   pageDown            page_down
--     --   cursorHome          home
--     --   cursorEnd           end
--     --   activate            enter, kp_enter
--     --   upToParentDir       alt+up
--     --   editPath            alt+d   (edits the pane's path in place)
--     --   switchPane          tab
--     --   otherPaneToSameDir  alt+o
--     --   swapPanes           ctrl+u
--     --   toggleMark          space
--     --   toggleMarkAndDown   insert
--     --   markAll             kp_add, ctrl+a
--     --   unmarkAll           kp_subtract, ctrl+d
--     --   invertMarks         kp_multiply
--     --   copy                F5
--     --   move                F6
--     --   makeDir             F7
--     --   delete              F8, delete
--     --   viewSmall           ctrl+1
--     --   viewLarge           ctrl+2
--     --   toggleView          ctrl+v
--     --   toggleHidden        ctrl+h
--     --   refresh             ctrl+r
--     --   quit                F10, ctrl+q
--     keys = {
--         -- ["ctrl+up"] = "upToParentDir",
--         -- ["delete"] = false,
--     },
-- }
