//! zoe's tree-sitter syntax highlighting: a registry that `dlopen`s
//! language parsers at runtime, and a `Highlighter` that keeps a parse
//! tree for the current buffer and turns it into per-line colour spans.
//!
//! **No grammar is compiled into zoe.** A "language" is a directory on
//! the grammar search path holding a `parser.so` -- a standalone
//! tree-sitter parser shared library exporting `tree_sitter_<name>` --
//! and a `highlights.scm` query. Adding a language is dropping such a
//! directory next to the others; see docs/decisions.md's zoe syntax
//! section. zoe links only libtree-sitter itself (the parse runtime and
//! the query engine) -- the grammars are data.
//!
//! **Highlighting is derived state, not editor state.** `editor.zig` /
//! `buffer.zig` stay pure and know nothing about colours. `Buffer` does
//! keep a small journal of the byte/point ranges it mutated (`Edit`) --
//! generic edit bookkeeping, not a highlighting hook -- and `ui.zig`
//! replays that journal onto the retained parse tree before each
//! reparse, so an edit is an incremental `Tree.edit` + reparse against
//! the old tree, not a whole-buffer parse. A full parse is still the
//! fallback (first parse, language switch, a journal that overflowed).
//!
//! **Injected languages.** After the primary parse, `injections.scm` (if
//! the grammar dir ships one) is run to find embedded regions -- a
//! fenced code block in Markdown, the `(inline)` span inside a Markdown
//! paragraph -- and each region is parsed with its own grammar over just
//! its byte ranges (`Parser.setIncludedRanges`). The child trees are
//! flat in `Highlighter.injections`, ordered shallowest-first, and
//! `lineSpans` paints them over the top of the primary layer so a deeper
//! layer's colour wins the bytes it covers. Injection recurses up to
//! `max_injection_depth` (Markdown block -> markdown_inline -> html).
//! Child trees are rebuilt from scratch each reparse -- they are small.
//!
//! Deliberate limitations, all documented in decisions.md:
//!   - No `locals.scm` (so no scope-aware local/parameter distinction).
//!   - Every content region of a given injected language is parsed on
//!     its own; there is no `injection.combined` handling.
//!   - Query predicates `#eq?` / `#not-eq?` / `#any-of?` / `#not-any-of?`
//!     are evaluated; a pattern carrying any other test predicate
//!     (`#match?`, `#lua-match?`, ...) is disabled wholesale rather than
//!     applied unconditionally, so we under-highlight instead of mis-
//!     highlighting.

const std = @import("std");
const ts = @import("tree_sitter");
const glyphwire = @import("glyphwire");
const buffer = @import("buffer.zig");

const Buffer = buffer.Buffer;
const Edit = buffer.Edit;
const Color = glyphwire.Color;

/// How many times injection recursion nests before it stops: a Markdown
/// block injecting `markdown_inline`, which itself injects `html`, is
/// depth 2. Past this a deeply self-injecting grammar just stops adding
/// layers.
pub const max_injection_depth: u8 = 3;

/// A half-open buffer byte range. `reparseIncremental` returns these for
/// the lines whose highlighting may have moved, so `ui.zig` can repaint
/// just those rows instead of the whole pane.
pub const ByteRange = struct { start: usize, end: usize };

fn pointOf(p: buffer.Pos) ts.Point {
    return .{ .row = @intCast(p.line), .column = @intCast(p.col) };
}

/// The oldest grammar ABI libtree-sitter here can parse. A `parser.so`
/// generated by a newer tree-sitter CLI than the runtime is rejected
/// with a clear message rather than crashing mid-parse.
pub const min_abi_version = ts.MIN_COMPATIBLE_LANGUAGE_VERSION;
pub const max_abi_version = ts.LANGUAGE_VERSION;

/// A run of one colour within a line, as byte offsets relative to the
/// line's first byte (its newline excluded). Non-overlapping and sorted
/// by `start`; a gap between spans means "the default text colour".
pub const Span = struct {
    start: usize,
    end: usize,
    color: Color,
};

/// Longest single line we bother to highlight. Past this the per-line
/// paint buffer is the dominant cost and a line that long is almost
/// always minified or generated anyway -- it renders in the plain
/// colour.
const max_highlight_line: usize = 1 << 15;

// ── Theme ───────────────────────────────────────────────────────────────

/// Maps a tree-sitter highlight capture name to a foreground colour.
///
/// Capture names are dotted and hierarchical (`string.special.key`); a
/// name with no colour of its own falls back to its prefix
/// (`string.special.key` -> `string.special` -> `string`). `null` for a
/// group means "don't colour it" -- the text keeps the pane's default.
pub const Theme = struct {
    colors: std.EnumArray(Group, ?Color),

    pub const Group = enum {
        comment,
        keyword,
        string,
        string_escape,
        string_special,
        escape,
        number,
        boolean,
        character,
        constant,
        constant_builtin,
        function,
        function_builtin,
        type,
        type_builtin,
        constructor,
        operator,
        property,
        variable,
        variable_builtin,
        variable_parameter,
        module,
        label,
        attribute,
        tag,
        punctuation,
        punctuation_special,
        text_title,
        text_literal,
        text_uri,
        text_reference,
    };

    /// The dotted capture names grammars actually emit, mapped to a
    /// group. `colorFor` walks a name down to its prefixes against this.
    const name_to_group = std.StaticStringMap(Group).initComptime(.{
        .{ "comment", .comment },
        .{ "keyword", .keyword },
        .{ "string", .string },
        .{ "string.escape", .string_escape },
        .{ "string.special", .string_special },
        .{ "escape", .escape },
        .{ "number", .number },
        .{ "float", .number },
        .{ "boolean", .boolean },
        .{ "character", .character },
        .{ "constant", .constant },
        .{ "constant.builtin", .constant_builtin },
        .{ "function", .function },
        .{ "function.builtin", .function_builtin },
        .{ "constructor", .constructor },
        .{ "type", .type },
        .{ "type.builtin", .type_builtin },
        .{ "operator", .operator },
        .{ "property", .property },
        .{ "field", .property },
        .{ "variable", .variable },
        .{ "variable.builtin", .variable_builtin },
        .{ "variable.parameter", .variable_parameter },
        .{ "variable.member", .property },
        .{ "parameter", .variable_parameter },
        .{ "module", .module },
        .{ "namespace", .module },
        .{ "import", .keyword },
        .{ "label", .label },
        .{ "attribute", .attribute },
        .{ "tag", .tag },
        .{ "punctuation", .punctuation },
        .{ "punctuation.special", .punctuation_special },
        .{ "text.title", .text_title },
        .{ "title", .text_title },
        .{ "text.literal", .text_literal },
        .{ "text.uri", .text_uri },
        .{ "text.reference", .text_reference },
    });

    fn rgb(hex: u24) Color {
        return .{
            .r = @intCast((hex >> 16) & 0xff),
            .g = @intCast((hex >> 8) & 0xff),
            .b = @intCast(hex & 0xff),
        };
    }

    /// A flat, dark palette in the spirit of the one in `ui.zig` --
    /// enough contrast between groups to read structure, nothing
    /// fluorescent. `variable` and `punctuation` are left uncoloured on
    /// purpose: colouring every identifier and bracket is noise.
    pub fn initDefault() Theme {
        var t = Theme{ .colors = std.EnumArray(Group, ?Color).initFill(null) };
        t.colors.set(.comment, rgb(0x5c6370));
        t.colors.set(.keyword, rgb(0xc678dd));
        t.colors.set(.string, rgb(0x98c379));
        t.colors.set(.string_escape, rgb(0x56b6c2));
        t.colors.set(.string_special, rgb(0x56b6c2));
        t.colors.set(.escape, rgb(0x56b6c2));
        t.colors.set(.number, rgb(0xd19a66));
        t.colors.set(.boolean, rgb(0xd19a66));
        t.colors.set(.character, rgb(0x98c379));
        t.colors.set(.constant, rgb(0xd19a66));
        t.colors.set(.constant_builtin, rgb(0xd19a66));
        t.colors.set(.function, rgb(0x61afef));
        t.colors.set(.function_builtin, rgb(0x61afef));
        t.colors.set(.type, rgb(0xe5c07b));
        t.colors.set(.type_builtin, rgb(0xe5c07b));
        t.colors.set(.constructor, rgb(0xe5c07b));
        t.colors.set(.operator, rgb(0x56b6c2));
        t.colors.set(.property, rgb(0xe06c75));
        t.colors.set(.variable_builtin, rgb(0xe06c75));
        t.colors.set(.variable_parameter, rgb(0xd19a66));
        t.colors.set(.module, rgb(0xe5c07b));
        t.colors.set(.label, rgb(0x61afef));
        t.colors.set(.attribute, rgb(0xd19a66));
        t.colors.set(.tag, rgb(0xe06c75));
        t.colors.set(.punctuation_special, rgb(0xc678dd));
        t.colors.set(.text_title, rgb(0x61afef));
        t.colors.set(.text_literal, rgb(0x98c379));
        t.colors.set(.text_uri, rgb(0x56b6c2));
        t.colors.set(.text_reference, rgb(0xe06c75));
        return t;
    }

    /// Override one group by its (undotted) name, e.g. `set("keyword",
    /// ...)`. An unknown name is ignored. Used by the Lua config.
    pub fn setByName(self: *Theme, name: []const u8, color: Color) bool {
        const g = name_to_group.get(name) orelse return false;
        self.colors.set(g, color);
        return true;
    }

    /// The colour for a capture name, or `null` for "leave it alone".
    pub fn colorFor(self: *const Theme, capture: []const u8) ?Color {
        var name = capture;
        while (true) {
            if (name_to_group.get(name)) |g| return self.colors.get(g);
            const dot = std.mem.lastIndexOfScalar(u8, name, '.') orelse return null;
            name = name[0..dot];
        }
    }
};

// ── Grammar registry ────────────────────────────────────────────────────

/// One `dlopen`ed grammar. The library and language pointer live for the
/// process -- tree-sitter language pointers must outlive every tree and
/// query built from them, and zoe only ever loads a grammar once, so it
/// is never closed.
pub const LoadedGrammar = struct {
    lib: std.DynLib,
    language: *const ts.Language,
    /// `highlights.scm` source, null-terminated, owned by the registry.
    highlights: [:0]u8,
    /// `injections.scm` source if the grammar dir had one, else null.
    /// Null-terminated, owned by the registry.
    injections: ?[:0]u8 = null,

    fn freeSources(self: *LoadedGrammar, alloc: std.mem.Allocator) void {
        alloc.free(self.highlights);
        if (self.injections) |inj| alloc.free(inj);
    }
};

/// Extension-to-grammar mapping, from the built-in defaults plus the Lua
/// config. `extensions` entries include the leading dot.
pub const LangDef = struct {
    name: []const u8,
    extensions: []const []const u8,
};

/// The six grammars `build.zig` compiles and installs. A config can add
/// more or remap these.
pub const default_langs = [_]LangDef{
    .{ .name = "zig", .extensions = &.{ ".zig", ".zon" } },
    .{ .name = "json", .extensions = &.{ ".json", ".jsonc" } },
    .{ .name = "c", .extensions = &.{ ".c", ".h" } },
    .{ .name = "python", .extensions = &.{ ".py", ".pyi" } },
    .{ .name = "toml", .extensions = &.{ ".toml" } },
    .{ .name = "markdown", .extensions = &.{ ".md", ".markdown" } },
};

/// The grammar directories to search, highest priority first:
///   1. `extra` (from `config.grammar_dirs`),
///   2. `$GLYPHWIRE_ZOE_GRAMMAR_DIR` (`:`-separated -- what `zig build`
///      points at the just-installed grammars),
///   3. `$XDG_CONFIG_HOME/glyphwire/zoe/grammars` (or `~/.config/...`),
///   4. `$XDG_DATA_HOME/glyphwire/grammars` (or `~/.local/share/...`),
///   5. `<exe dir>/../share/glyphwire/grammars` (an installed tree).
///
/// Every element is owned by `alloc`; free each, then the slice. Missing
/// env vars just drop their entry.
pub fn searchDirs(
    alloc: std.mem.Allocator,
    io: std.Io,
    environ: *const std.process.Environ.Map,
    extra: []const []const u8,
) ![]const []const u8 {
    var dirs: std.ArrayList([]const u8) = .empty;
    errdefer {
        for (dirs.items) |d| alloc.free(d);
        dirs.deinit(alloc);
    }

    for (extra) |d| try dirs.append(alloc, try alloc.dupe(u8, d));

    if (environ.get("GLYPHWIRE_ZOE_GRAMMAR_DIR")) |v| {
        var it = std.mem.tokenizeScalar(u8, v, ':');
        while (it.next()) |part| try dirs.append(alloc, try alloc.dupe(u8, part));
    }

    if (environ.get("XDG_CONFIG_HOME")) |xdg| {
        if (xdg.len > 0) try dirs.append(alloc, try std.fs.path.join(alloc, &.{ xdg, "glyphwire", "zoe", "grammars" }));
    } else if (environ.get("HOME")) |home| {
        try dirs.append(alloc, try std.fs.path.join(alloc, &.{ home, ".config", "glyphwire", "zoe", "grammars" }));
    }

    if (environ.get("XDG_DATA_HOME")) |xdg| {
        if (xdg.len > 0) try dirs.append(alloc, try std.fs.path.join(alloc, &.{ xdg, "glyphwire", "grammars" }));
    } else if (environ.get("HOME")) |home| {
        try dirs.append(alloc, try std.fs.path.join(alloc, &.{ home, ".local", "share", "glyphwire", "grammars" }));
    }

    if (std.process.executableDirPathAlloc(io, alloc)) |exe_dir| {
        defer alloc.free(exe_dir);
        try dirs.append(alloc, try std.fs.path.join(alloc, &.{ exe_dir, "..", "share", "glyphwire", "grammars" }));
    } else |_| {}

    return dirs.toOwnedSlice(alloc);
}

pub const Registry = struct {
    alloc: std.mem.Allocator,
    io: std.Io,
    /// Grammar directories, highest priority first. Owned.
    search_dirs: []const []const u8,
    /// Extension mapping, highest priority first (first match wins).
    /// Owned; strings borrowed from whatever built it (config arena or
    /// `default_langs`).
    langs: []const LangDef,
    /// name -> loaded grammar. Keys owned; values are boxed so the
    /// pointer `get` hands back stays valid across a later `get` that
    /// resizes the map.
    loaded: std.StringHashMapUnmanaged(*LoadedGrammar) = .empty,
    /// Names we tried and couldn't load, so a miss is logged once, not
    /// every keystroke. Keys owned.
    failed: std.StringHashMapUnmanaged(void) = .empty,

    pub fn init(
        alloc: std.mem.Allocator,
        io: std.Io,
        search_dirs: []const []const u8,
        langs: []const LangDef,
    ) Registry {
        return .{ .alloc = alloc, .io = io, .search_dirs = search_dirs, .langs = langs };
    }

    pub fn deinit(self: *Registry) void {
        var it = self.loaded.iterator();
        while (it.next()) |e| {
            e.value_ptr.*.freeSources(self.alloc);
            // e.value_ptr.*.lib is intentionally not closed (see LoadedGrammar).
            self.alloc.destroy(e.value_ptr.*);
            self.alloc.free(e.key_ptr.*);
        }
        self.loaded.deinit(self.alloc);

        var fit = self.failed.keyIterator();
        while (fit.next()) |k| self.alloc.free(k.*);
        self.failed.deinit(self.alloc);
    }

    /// The grammar name for a file path, matched on its extension
    /// (case-insensitively). `null` when nothing maps.
    pub fn nameForPath(self: *const Registry, path: []const u8) ?[]const u8 {
        const ext = std.fs.path.extension(path);
        if (ext.len == 0) return null;
        for (self.langs) |l| {
            for (l.extensions) |e| {
                if (std.ascii.eqlIgnoreCase(e, ext)) return l.name;
            }
        }
        return null;
    }

    /// Spellings an `injections.scm` may use for a language that our
    /// grammar directories know under another name.
    const lang_aliases = std.StaticStringMap([]const u8).initComptime(.{
        .{ "markdown.inline", "markdown_inline" },
        .{ "md", "markdown" },
        .{ "py", "python" },
        .{ "py3", "python" },
    });

    /// The grammar-directory name for a possibly-aliased language name.
    pub fn resolveAlias(name: []const u8) []const u8 {
        return lang_aliases.get(name) orelse name;
    }

    /// The loaded grammar for `name`, `dlopen`ing it on first use.
    /// `null` (logged once) when no directory on the search path has a
    /// usable `parser.so` + `highlights.scm` for it. `name` is resolved
    /// through `resolveAlias` first, so an injection query naming
    /// `markdown.inline` finds the `markdown_inline` directory.
    pub fn get(self: *Registry, raw_name: []const u8) ?*LoadedGrammar {
        const name = resolveAlias(raw_name);
        if (self.loaded.get(name)) |g| return g;
        if (self.failed.contains(name)) return null;

        if (self.load(name)) |g| {
            var loaded = g;
            const box = self.alloc.create(LoadedGrammar) catch {
                loaded.freeSources(self.alloc);
                loaded.lib.close();
                return null;
            };
            box.* = loaded;
            const key = self.alloc.dupe(u8, name) catch {
                box.freeSources(self.alloc);
                box.lib.close();
                self.alloc.destroy(box);
                return null;
            };
            self.loaded.put(self.alloc, key, box) catch {
                self.alloc.free(key);
                box.freeSources(self.alloc);
                box.lib.close();
                self.alloc.destroy(box);
                return null;
            };
            return box;
        } else |err| {
            std.log.warn("zoe: no usable '{s}' grammar on the search path ({t})", .{ name, err });
            const key = self.alloc.dupe(u8, name) catch return null;
            self.failed.put(self.alloc, key, {}) catch self.alloc.free(key);
            return null;
        }
    }

    const LoadError = error{ NotFound, BadAbi, OutOfMemory };

    fn load(self: *Registry, name: []const u8) LoadError!LoadedGrammar {
        const so_names = [_][]const u8{
            "parser.so",
            // `build.zig` installs the artifact under its own name.
            std.fmt.allocPrint(self.alloc, "libtree-sitter-{s}.so", .{name}) catch return error.OutOfMemory,
            std.fmt.allocPrint(self.alloc, "{s}.so", .{name}) catch return error.OutOfMemory,
        };
        defer self.alloc.free(so_names[1]);
        defer self.alloc.free(so_names[2]);

        const sym = symbolName(self.alloc, name) catch return error.OutOfMemory;
        defer self.alloc.free(sym);
        const LangFn = *const fn () callconv(.c) *const ts.Language;

        for (self.search_dirs) |dir| {
            for (so_names) |so| {
                const so_path = std.fs.path.join(self.alloc, &.{ dir, name, so }) catch return error.OutOfMemory;
                defer self.alloc.free(so_path);

                var lib = std.DynLib.open(so_path) catch continue;

                const lang_fn = lib.lookup(LangFn, sym) orelse {
                    lib.close();
                    continue;
                };
                const language = lang_fn();

                const abi = language.abiVersion();
                if (abi < ts.MIN_COMPATIBLE_LANGUAGE_VERSION or abi > ts.LANGUAGE_VERSION) {
                    std.log.warn(
                        "zoe: '{s}' grammar ABI {d} unsupported (need {d}..{d}); rebuild it",
                        .{ name, abi, ts.MIN_COMPATIBLE_LANGUAGE_VERSION, ts.LANGUAGE_VERSION },
                    );
                    lib.close();
                    return error.BadAbi;
                }

                const q_path = std.fs.path.join(self.alloc, &.{ dir, name, "highlights.scm" }) catch {
                    lib.close();
                    return error.OutOfMemory;
                };
                defer self.alloc.free(q_path);
                const scm = std.Io.Dir.cwd().readFileAllocOptions(
                    self.io,
                    q_path,
                    self.alloc,
                    .limited(4 * 1024 * 1024),
                    .of(u8),
                    0,
                ) catch {
                    lib.close();
                    continue;
                };

                // `injections.scm` is optional -- a grammar with no
                // embedded languages simply doesn't ship one.
                const inj = self.readOptionalQuery(dir, name, "injections.scm");

                return .{ .lib = lib, .language = language, .highlights = scm, .injections = inj };
            }
        }
        return error.NotFound;
    }

    /// Reads `<dir>/<name>/<file>` as a null-terminated string, or null
    /// if it isn't there / can't be read. Used for the optional query
    /// files (`injections.scm`); a missing one is not an error.
    fn readOptionalQuery(self: *Registry, dir: []const u8, name: []const u8, file: []const u8) ?[:0]u8 {
        const path = std.fs.path.join(self.alloc, &.{ dir, name, file }) catch return null;
        defer self.alloc.free(path);
        return std.Io.Dir.cwd().readFileAllocOptions(
            self.io,
            path,
            self.alloc,
            .limited(4 * 1024 * 1024),
            .of(u8),
            0,
        ) catch null;
    }

    /// `tree_sitter_<name>`, with `-` turned into `_` the way the
    /// tree-sitter CLI does when it generates the entry point.
    fn symbolName(alloc: std.mem.Allocator, name: []const u8) ![:0]u8 {
        const sym = try std.fmt.allocPrintSentinel(alloc, "tree_sitter_{s}", .{name}, 0);
        for (sym) |*c| {
            if (c.* == '-') c.* = '_';
        }
        return sym;
    }
};

// ── Highlighter ─────────────────────────────────────────────────────────

const Predicate = struct {
    const Kind = enum { eq, not_eq, any_of, not_any_of };
    const Arg = union(enum) { capture: u32, text: []const u8 };

    kind: Kind,
    /// The capture the predicate constrains (its first `@arg`).
    capture: u32,
    args: []const Arg,
};

/// Everything needed to highlight one language, compiled once and reused
/// across every injected region of that language and every reparse until
/// `clearLanguage`. The primary language keeps its equivalents as
/// individual `Highlighter` fields; this is only for injected ones.
const CompiledLang = struct {
    /// Borrowed from the `compiled` map key.
    name: []const u8,
    /// Owned. Its language is set; injected regions parse through it one
    /// at a time (`setIncludedRanges` then `parseString`).
    parser: *ts.Parser,
    /// Owned. `highlights.scm`.
    query: *ts.Query,
    /// Owned. `injections.scm` compiled, for nested injection; null when
    /// the grammar ships none.
    inj_query: ?*ts.Query = null,
    /// Owned. capture id -> colour, resolved against the theme.
    capture_colors: []?Color = &.{},
    /// Owned. pattern index -> predicates (see `Highlighter.pattern_preds`).
    pattern_preds: []const []const Predicate = &.{},

    fn deinit(self: *CompiledLang, alloc: std.mem.Allocator) void {
        self.parser.destroy();
        self.query.destroy();
        if (self.inj_query) |q| q.destroy();
        alloc.free(self.capture_colors);
        freePreds(alloc, self.pattern_preds);
    }
};

/// One resolved embedded region: a child grammar's parse tree over a set
/// of byte ranges of the same `Highlighter.source`. Trees are rebuilt
/// from scratch each reparse (they are small); `compiled` outlives them.
const Injection = struct {
    /// Borrowed from the `compiled` map key.
    lang_name: []const u8,
    /// Owned.
    tree: *ts.Tree,
    /// Borrowed from the `compiled` map.
    compiled: *CompiledLang,
    /// Owned. The included ranges this tree was parsed over, in buffer
    /// coordinates -- `lineSpans` uses them to skip layers off the line.
    ranges: []ts.Range,
};

pub const Highlighter = struct {
    alloc: std.mem.Allocator,
    theme: Theme,
    parser: *ts.Parser,
    cursor: *ts.QueryCursor,
    /// A second cursor, used only while resolving injections, so nested
    /// resolution can re-`exec` without disturbing an outer walk.
    inj_cursor: *ts.QueryCursor,

    /// The grammar name currently set, borrowed from the registry's key.
    lang_name: ?[]const u8 = null,
    query: ?*ts.Query = null,
    tree: ?*ts.Tree = null,
    /// The exact bytes `tree` was parsed from -- kept so `#eq?` /
    /// `#any-of?` can read a captured node's text. Owned.
    source: []u8 = &.{},

    /// capture id -> resolved colour (or null = don't colour). Rebuilt
    /// by `setLanguage`. Owned.
    capture_colors: []?Color = &.{},
    /// pattern index -> the predicates to check before applying its
    /// captures. A disabled pattern gets an empty slice. Owned (each
    /// inner `args` slice too).
    pattern_preds: []const []const Predicate = &.{},

    /// The registry to resolve injected grammars through, and whether to
    /// attempt injection at all. Set once via `configureInjections`,
    /// before `setLanguage`; both survive a language switch.
    registry: ?*Registry = null,
    injections_enabled: bool = true,
    /// The primary language's `injections.scm` compiled, or null (no
    /// grammar file, injection disabled, or a bad query). Owned.
    inj_query: ?*ts.Query = null,
    /// Resolved embedded regions, shallowest first. Rebuilt every
    /// reparse. Owned.
    injections: std.ArrayList(Injection) = .empty,
    /// canonical language name -> its compiled artifacts, shared across
    /// injections and reparses. Keys owned; values boxed and owned.
    compiled: std.StringHashMapUnmanaged(*CompiledLang) = .empty,
    /// Injected languages we tried and couldn't compile, so a miss is
    /// silent after the first. Keys owned.
    compiled_failed: std.StringHashMapUnmanaged(void) = .empty,

    /// Per-line scratch: one entry per byte of the line, holding the
    /// winning colour so far. Reused across calls.
    paint: std.ArrayList(?Color) = .empty,
    raw: std.ArrayList(RawSpan) = .empty,

    const RawSpan = struct { start: usize, end: usize, specificity: u32, color: Color };

    pub fn init(alloc: std.mem.Allocator, theme: Theme) !Highlighter {
        const parser = ts.Parser.create();
        errdefer parser.destroy();
        const cursor = ts.QueryCursor.create();
        errdefer cursor.destroy();
        const inj_cursor = ts.QueryCursor.create();
        return .{
            .alloc = alloc,
            .theme = theme,
            .parser = parser,
            .cursor = cursor,
            .inj_cursor = inj_cursor,
        };
    }

    pub fn deinit(self: *Highlighter) void {
        self.clearLanguage();
        self.cursor.destroy();
        self.inj_cursor.destroy();
        self.parser.destroy();
        self.injections.deinit(self.alloc);
        self.compiled.deinit(self.alloc);
        self.compiled_failed.deinit(self.alloc);
        self.paint.deinit(self.alloc);
        self.raw.deinit(self.alloc);
        self.* = undefined;
    }

    /// Give the highlighter the registry it resolves injected grammars
    /// through, and whether injection is on. Call before `setLanguage`.
    /// With no registry (or `enabled` false) injection is simply not
    /// attempted and only `highlights.scm` of the primary grammar runs.
    pub fn configureInjections(self: *Highlighter, registry: ?*Registry, enabled: bool) void {
        self.registry = registry;
        self.injections_enabled = enabled;
    }

    /// A language has been chosen (its query compiled).
    pub fn languageSet(self: *const Highlighter) bool {
        return self.query != null;
    }

    /// A language is chosen *and* the current buffer has been parsed --
    /// `lineSpans` will do something.
    pub fn ready(self: *const Highlighter) bool {
        return self.query != null and self.tree != null;
    }

    pub fn clearLanguage(self: *Highlighter) void {
        self.clearInjections();

        var cit = self.compiled.iterator();
        while (cit.next()) |e| {
            e.value_ptr.*.deinit(self.alloc);
            self.alloc.destroy(e.value_ptr.*);
            self.alloc.free(e.key_ptr.*);
        }
        self.compiled.clearRetainingCapacity();

        var fit = self.compiled_failed.keyIterator();
        while (fit.next()) |k| self.alloc.free(k.*);
        self.compiled_failed.clearRetainingCapacity();

        if (self.inj_query) |q| {
            q.destroy();
            self.inj_query = null;
        }
        if (self.tree) |t| {
            t.destroy();
            self.tree = null;
        }
        if (self.query) |q| {
            q.destroy();
            self.query = null;
        }
        self.parser.setLanguage(null) catch {};
        self.alloc.free(self.source);
        self.source = &.{};
        self.alloc.free(self.capture_colors);
        self.capture_colors = &.{};
        freePreds(self.alloc, self.pattern_preds);
        self.pattern_preds = &.{};
        self.lang_name = null;
    }

    /// Drop every resolved injection tree. The compiled-language cache
    /// (`compiled`) is kept -- only the trees and their range slices go.
    fn clearInjections(self: *Highlighter) void {
        for (self.injections.items) |*inj| {
            inj.tree.destroy();
            self.alloc.free(inj.ranges);
        }
        self.injections.clearRetainingCapacity();
    }

    /// Switch to `grammar` (which outlives the Highlighter -- the
    /// registry owns it). Compiles `highlights.scm` (and, if injection is
    /// on and the grammar ships one, `injections.scm`) and resolves the
    /// highlight captures against the theme. On any failure the
    /// Highlighter is left with no language and the caller falls back to
    /// plain text.
    pub fn setLanguage(self: *Highlighter, name: []const u8, grammar: *const LoadedGrammar) !void {
        self.clearLanguage();

        self.parser.setLanguage(grammar.language) catch |e| {
            std.log.warn("zoe: parser rejected '{s}' grammar ({t})", .{ name, e });
            return error.IncompatibleGrammar;
        };

        var err_off: u32 = 0;
        const q = ts.Query.create(grammar.language, grammar.highlights, &err_off) catch |e| {
            std.log.warn("zoe: '{s}' highlights.scm rejected ({t}) at byte {d}", .{ name, e, err_off });
            self.parser.setLanguage(null) catch {};
            return error.BadQuery;
        };
        errdefer {
            q.destroy();
            self.parser.setLanguage(null) catch {};
        }

        // Build the fallible pieces first, then publish them together --
        // a failure here leaves `self` with no language, not a half-set one.
        const colors = try resolveCaptureColors(self.alloc, &self.theme, q);
        errdefer self.alloc.free(colors);
        const preds = try buildPredicates(self.alloc, q);
        errdefer freePreds(self.alloc, preds);

        self.query = q;
        self.lang_name = name;
        self.capture_colors = colors;
        self.pattern_preds = preds;

        if (self.injections_enabled and self.registry != null) {
            if (grammar.injections) |src| {
                var ie: u32 = 0;
                self.inj_query = ts.Query.create(grammar.language, src, &ie) catch |e| blk: {
                    std.log.warn("zoe: '{s}' injections.scm rejected ({t}) at byte {d}", .{ name, e, ie });
                    break :blk null;
                };
            }
        }
    }

    /// Reparse the whole buffer from scratch (no tree reuse) and rebuild
    /// every injection. The fallback path: first parse, language switch,
    /// or an edit journal that overflowed.
    pub fn reparse(self: *Highlighter, buf: *const Buffer) !void {
        if (self.query == null) return;

        const src = try buf.text(self.alloc);
        errdefer self.alloc.free(src);

        const new_tree = self.parser.parseString(src, null) orelse return error.ParseFailed;

        if (self.tree) |t| t.destroy();
        self.tree = new_tree;
        self.alloc.free(self.source);
        self.source = src;

        self.clearInjections();
        self.resolveInjections() catch {};
    }

    /// Replay one buffer mutation onto the retained tree so the next
    /// `reparseIncremental` can reuse it. No-op until there is a tree.
    pub fn applyEdit(self: *Highlighter, e: Edit) void {
        const t = self.tree orelse return;
        t.edit(.{
            .start_byte = @intCast(e.start_byte),
            .old_end_byte = @intCast(e.old_end_byte),
            .new_end_byte = @intCast(e.new_end_byte),
            .start_point = pointOf(e.start_point),
            .old_end_point = pointOf(e.old_end_point),
            .new_end_point = pointOf(e.new_end_point),
        });
    }

    /// Reparse against the retained tree (already brought in sync by
    /// `applyEdit`). Appends to `changed` the buffer byte ranges whose
    /// syntax structure moved between the old tree and the new one.
    ///
    /// Returns false when the caller should still repaint the whole
    /// visible pane -- no tree was retained to diff against, or the set
    /// of injected regions changed (a code fence added or its language
    /// edited); true when `changed`, unioned with the caller's own
    /// edited-line set, is a complete account of what must be redrawn.
    pub fn reparseIncremental(
        self: *Highlighter,
        buf: *const Buffer,
        changed: *std.ArrayList(ByteRange),
    ) !bool {
        if (self.query == null) return false;
        const old = self.tree orelse {
            try self.reparse(buf);
            return false;
        };

        const src = try buf.text(self.alloc);
        errdefer self.alloc.free(src);

        const new_tree = self.parser.parseString(src, old) orelse return error.ParseFailed;

        const ranges: []const ts.Range = old.getChangedRanges(self.alloc, new_tree) catch &.{};
        defer if (ranges.len > 0) self.alloc.free(ranges);
        for (ranges) |r| try changed.append(self.alloc, .{ .start = r.start_byte, .end = r.end_byte });

        old.destroy();
        self.tree = new_tree;
        self.alloc.free(self.source);
        self.source = src;

        const before = self.injectionSignature();
        self.clearInjections();
        self.resolveInjections() catch {};
        return before == self.injectionSignature();
    }

    // ── Injection resolution ───────────────────────────────────────────

    /// (Re)build `injections` from the primary tree's `injections.scm`.
    fn resolveInjections(self: *Highlighter) !void {
        if (!self.injections_enabled) return;
        if (self.registry == null) return;
        const iq = self.inj_query orelse return;
        const tree = self.tree orelse return;
        try self.collectInjections(iq, tree, 1);
    }

    const InjPair = struct { lang: []const u8, ranges: []ts.Range };

    /// Runs `iq` over `tree`, and for every `@injection.content` region
    /// with a resolvable language, parses a child tree and appends it to
    /// `injections`; then recurses into that child's own injections.
    fn collectInjections(self: *Highlighter, iq: *ts.Query, tree: *ts.Tree, depth: u8) !void {
        if (depth > max_injection_depth) return;

        const content_cap = queryCaptureId(iq, "injection.content") orelse return;
        const lang_cap = queryCaptureId(iq, "injection.language");

        // Phase 1: drain the cursor into a list, so the recursion in
        // phase 2 can re-`exec` the same cursor freely.
        var pairs: std.ArrayList(InjPair) = .empty;
        defer {
            for (pairs.items) |p| self.alloc.free(p.ranges);
            pairs.deinit(self.alloc);
        }

        self.inj_cursor.setByteRange(0, std.math.maxInt(u32)) catch {};
        self.inj_cursor.exec(iq, tree.rootNode());
        while (self.inj_cursor.nextMatch()) |m| {
            var lang: ?[]const u8 = staticInjectionLang(iq, m.pattern_index);
            if (lang_cap) |lc| {
                for (m.captures) |cap| {
                    if (cap.index != lc) continue;
                    const s: usize = cap.node.startByte();
                    const e: usize = cap.node.endByte();
                    if (e <= self.source.len and s <= e)
                        lang = std.mem.trim(u8, self.source[s..e], " \t\r\n");
                }
            }
            const lname = lang orelse continue;
            if (lname.len == 0) continue;

            var ranges: std.ArrayList(ts.Range) = .empty;
            defer ranges.deinit(self.alloc);
            for (m.captures) |cap| {
                if (cap.index != content_cap) continue;
                const r = cap.node.range();
                if (r.end_byte > r.start_byte) try ranges.append(self.alloc, r);
            }
            if (ranges.items.len == 0) continue;

            const slice = try ranges.toOwnedSlice(self.alloc);
            errdefer self.alloc.free(slice);
            try pairs.append(self.alloc, .{ .lang = lname, .ranges = slice });
        }

        // Phase 2: parse each region's child grammar and recurse.
        for (pairs.items) |p| {
            const child = (self.getCompiled(p.lang) catch continue) orelse continue;

            child.parser.setIncludedRanges(p.ranges) catch continue;
            const child_tree = child.parser.parseString(self.source, null);
            child.parser.setIncludedRanges(null) catch {};
            const ct = child_tree orelse continue;

            const owned = self.alloc.dupe(ts.Range, p.ranges) catch {
                ct.destroy();
                continue;
            };
            self.injections.append(self.alloc, .{
                .lang_name = child.name,
                .tree = ct,
                .compiled = child,
                .ranges = owned,
            }) catch {
                ct.destroy();
                self.alloc.free(owned);
                continue;
            };

            if (child.inj_query) |ciq| try self.collectInjections(ciq, ct, depth + 1);
        }
    }

    /// The compiled artifacts for an injected language, compiling and
    /// caching them on first use. `null` (remembered) when the grammar
    /// isn't on the search path or its query won't compile.
    fn getCompiled(self: *Highlighter, name: []const u8) !?*CompiledLang {
        const reg = self.registry orelse return null;
        const canon = Registry.resolveAlias(name);
        if (self.compiled.get(canon)) |c| return c;
        if (self.compiled_failed.contains(canon)) return null;

        const grammar = reg.get(canon) orelse {
            self.markCompiledFailed(canon);
            return null;
        };
        const c = self.compileLang(grammar) catch {
            self.markCompiledFailed(canon);
            return null;
        };
        const key = self.alloc.dupe(u8, canon) catch {
            c.deinit(self.alloc);
            self.alloc.destroy(c);
            return null;
        };
        self.compiled.put(self.alloc, key, c) catch {
            self.alloc.free(key);
            c.deinit(self.alloc);
            self.alloc.destroy(c);
            return null;
        };
        c.name = key;
        return c;
    }

    fn compileLang(self: *Highlighter, grammar: *const LoadedGrammar) !*CompiledLang {
        const parser = ts.Parser.create();
        errdefer parser.destroy();
        parser.setLanguage(grammar.language) catch return error.IncompatibleGrammar;

        var eoff: u32 = 0;
        const q = try ts.Query.create(grammar.language, grammar.highlights, &eoff);
        errdefer q.destroy();

        const iq: ?*ts.Query = if (grammar.injections) |src| blk: {
            var e2: u32 = 0;
            break :blk ts.Query.create(grammar.language, src, &e2) catch null;
        } else null;
        errdefer if (iq) |x| x.destroy();

        const colors = try resolveCaptureColors(self.alloc, &self.theme, q);
        errdefer self.alloc.free(colors);
        const preds = try buildPredicates(self.alloc, q);
        errdefer freePreds(self.alloc, preds);

        const box = try self.alloc.create(CompiledLang);
        box.* = .{
            .name = &.{},
            .parser = parser,
            .query = q,
            .inj_query = iq,
            .capture_colors = colors,
            .pattern_preds = preds,
        };
        return box;
    }

    fn markCompiledFailed(self: *Highlighter, name: []const u8) void {
        if (self.compiled_failed.contains(name)) return;
        const key = self.alloc.dupe(u8, name) catch return;
        self.compiled_failed.put(self.alloc, key, {}) catch self.alloc.free(key);
    }

    /// A cheap fingerprint of the current injection layout (languages and
    /// range bounds) so an incremental reparse can tell whether the
    /// embedded regions moved.
    fn injectionSignature(self: *const Highlighter) u64 {
        var h = std.hash.Wyhash.init(0);
        for (self.injections.items) |inj| {
            h.update(inj.lang_name);
            for (inj.ranges) |r| {
                h.update(std.mem.asBytes(&r.start_byte));
                h.update(std.mem.asBytes(&r.end_byte));
            }
            h.update(&[_]u8{0xff});
        }
        return h.final();
    }

    // ── Per-line painting ──────────────────────────────────────────────

    /// Fill `out` (cleared first) with the colour spans covering buffer
    /// byte range `[line_start, line_end)`, as offsets relative to
    /// `line_start`. The primary layer is painted first, then each
    /// injection that touches the line, so a deeper layer's colour wins.
    pub fn lineSpans(self: *Highlighter, line_start: usize, line_end: usize, out: *std.ArrayList(Span)) !void {
        out.clearRetainingCapacity();
        const q = self.query orelse return;
        const tree = self.tree orelse return;
        const line_len = line_end -| line_start;
        if (line_len == 0 or line_len > max_highlight_line) return;

        try self.paint.resize(self.alloc, line_len);
        @memset(self.paint.items, null);

        try self.paintLayer(q, tree, self.capture_colors, self.pattern_preds, line_start, line_end);
        for (self.injections.items) |*inj| {
            if (!rangesTouchLine(inj.ranges, line_start, line_end)) continue;
            try self.paintLayer(
                inj.compiled.query,
                inj.tree,
                inj.compiled.capture_colors,
                inj.compiled.pattern_preds,
                line_start,
                line_end,
            );
        }

        var i: usize = 0;
        while (i < line_len) {
            const c = self.paint.items[i];
            var j = i + 1;
            while (j < line_len and colorEql(self.paint.items[j], c)) j += 1;
            if (c) |col| try out.append(self.alloc, .{ .start = i, .end = j, .color = col });
            i = j;
        }
    }

    /// Runs one layer's query clipped to `[line_start, line_end)` and
    /// blends its captures into `self.paint` (already sized to the line).
    fn paintLayer(
        self: *Highlighter,
        q: *ts.Query,
        tree: *ts.Tree,
        colors: []const ?Color,
        preds: []const []const Predicate,
        line_start: usize,
        line_end: usize,
    ) !void {
        self.raw.clearRetainingCapacity();
        self.cursor.setByteRange(@intCast(line_start), @intCast(line_end)) catch {};
        self.cursor.exec(q, tree.rootNode());

        while (self.cursor.nextMatch()) |m| {
            if (!predicatesOk(self.source, preds, m)) continue;
            for (m.captures) |cap| {
                if (cap.index >= colors.len) continue;
                const color = colors[cap.index] orelse continue;
                const s: usize = cap.node.startByte();
                const e: usize = cap.node.endByte();
                if (e <= line_start or s >= line_end) continue;
                const cs = if (s > line_start) s - line_start else 0;
                const ce = (if (e < line_end) e else line_end) - line_start;
                if (ce <= cs) continue;
                try self.raw.append(self.alloc, .{
                    .start = cs,
                    .end = ce,
                    .specificity = @intCast(e - s),
                    .color = color,
                });
            }
        }
        if (self.raw.items.len == 0) return;

        // Paint less-specific (wider) captures first so a nested, more-
        // specific capture wins the bytes it covers. Stable sort keeps
        // "a later match wins on a tie", matching tree-sitter's own
        // last-wins convention.
        std.sort.insertion(RawSpan, self.raw.items, {}, lessSpecificFirst);
        for (self.raw.items) |r| {
            @memset(self.paint.items[r.start..r.end], r.color);
        }
    }
};

/// capture id -> theme colour (or null = don't colour), as a fresh
/// owned slice.
fn resolveCaptureColors(alloc: std.mem.Allocator, theme: *const Theme, q: *const ts.Query) ![]?Color {
    const n = q.captureCount();
    const colors = try alloc.alloc(?Color, n);
    var i: u32 = 0;
    while (i < n) : (i += 1) {
        colors[i] = theme.colorFor(q.captureNameForId(i) orelse "");
    }
    return colors;
}

/// pattern index -> the `#eq?` / `#any-of?` family predicates guarding
/// it. A pattern carrying a predicate we can't evaluate is disabled on
/// `q` and gets an empty slice. Owned (each inner `args` slice too);
/// free with `freePreds`.
fn buildPredicates(alloc: std.mem.Allocator, q: *ts.Query) ![]const []const Predicate {
    const pn = q.patternCount();
    const out = try alloc.alloc([]const Predicate, pn);
    errdefer alloc.free(out);
    var built: usize = 0;
    errdefer for (out[0..built]) |preds| {
        for (preds) |p| alloc.free(p.args);
        alloc.free(preds);
    };

    var p: u32 = 0;
    while (p < pn) : (p += 1) {
        var list: std.ArrayList(Predicate) = .empty;
        errdefer {
            for (list.items) |it| alloc.free(it.args);
            list.deinit(alloc);
        }

        const steps = q.predicatesForPattern(p);
        var disable = false;
        var i: usize = 0;
        while (i < steps.len) {
            var j = i;
            while (j < steps.len and steps[j].type != .done) j += 1;
            const grp = steps[i..j];
            i = j + 1;
            if (grp.len == 0 or grp[0].type != .string) continue;

            const pname = q.stringValueForId(grp[0].value_id) orelse continue;
            const kind: Predicate.Kind = if (std.mem.eql(u8, pname, "eq?"))
                .eq
            else if (std.mem.eql(u8, pname, "not-eq?"))
                .not_eq
            else if (std.mem.eql(u8, pname, "any-of?"))
                .any_of
            else if (std.mem.eql(u8, pname, "not-any-of?"))
                .not_any_of
            else {
                // A `!` step is a directive (`#set!`), harmless to
                // ignore. Any other `?` test we can't evaluate, so the
                // whole pattern is dropped rather than applied blind.
                if (std.mem.endsWith(u8, pname, "?")) disable = true;
                continue;
            };

            if (grp.len < 2 or grp[1].type != .capture) continue;
            var args: std.ArrayList(Predicate.Arg) = .empty;
            errdefer args.deinit(alloc);
            for (grp[2..]) |st| switch (st.type) {
                .capture => try args.append(alloc, .{ .capture = st.value_id }),
                .string => try args.append(alloc, .{ .text = q.stringValueForId(st.value_id) orelse "" }),
                .done => {},
            };
            try list.append(alloc, .{
                .kind = kind,
                .capture = grp[1].value_id,
                .args = try args.toOwnedSlice(alloc),
            });
        }

        if (disable) {
            q.disablePattern(p);
            for (list.items) |it| alloc.free(it.args);
            list.clearRetainingCapacity();
        }
        out[p] = try list.toOwnedSlice(alloc);
        built += 1;
    }
    return out;
}

fn freePreds(alloc: std.mem.Allocator, preds: []const []const Predicate) void {
    for (preds) |per_pattern| {
        for (per_pattern) |p| alloc.free(p.args);
        alloc.free(per_pattern);
    }
    alloc.free(preds);
}

fn predicatesOk(source: []const u8, preds: []const []const Predicate, m: ts.Query.Match) bool {
    if (m.pattern_index >= preds.len) return true;
    for (preds[m.pattern_index]) |pr| {
        const lhs = captureText(source, m, pr.capture) orelse return false;
        switch (pr.kind) {
            .eq, .not_eq => {
                if (pr.args.len == 0) continue;
                const rhs = switch (pr.args[0]) {
                    .capture => |c| captureText(source, m, c) orelse return false,
                    .text => |t| t,
                };
                const equal = std.mem.eql(u8, lhs, rhs);
                if ((pr.kind == .eq) != equal) return false;
            },
            .any_of, .not_any_of => {
                var found = false;
                for (pr.args) |a| {
                    const s = switch (a) {
                        .capture => |c| captureText(source, m, c) orelse continue,
                        .text => |t| t,
                    };
                    if (std.mem.eql(u8, lhs, s)) {
                        found = true;
                        break;
                    }
                }
                if ((pr.kind == .any_of) != found) return false;
            },
        }
    }
    return true;
}

fn captureText(source: []const u8, m: ts.Query.Match, capture_id: u32) ?[]const u8 {
    for (m.captures) |cap| {
        if (cap.index != capture_id) continue;
        const s: usize = cap.node.startByte();
        const e: usize = cap.node.endByte();
        if (e > source.len or s > e) return null;
        return source[s..e];
    }
    return null;
}

/// The static `#set! injection.language "x"` value for a pattern, if it
/// has one.
fn staticInjectionLang(q: *const ts.Query, pattern_index: u16) ?[]const u8 {
    const steps = q.predicatesForPattern(pattern_index);
    var i: usize = 0;
    while (i < steps.len) {
        var j = i;
        while (j < steps.len and steps[j].type != .done) j += 1;
        const grp = steps[i..j];
        i = j + 1;
        if (grp.len < 3 or grp[0].type != .string) continue;
        const pname = q.stringValueForId(grp[0].value_id) orelse continue;
        if (!std.mem.eql(u8, pname, "set!")) continue;
        if (grp[1].type != .string or grp[2].type != .string) continue;
        const key = q.stringValueForId(grp[1].value_id) orelse continue;
        if (std.mem.eql(u8, key, "injection.language"))
            return q.stringValueForId(grp[2].value_id);
    }
    return null;
}

/// The capture id for `name` in `q`, or null if it has no such capture.
fn queryCaptureId(q: *const ts.Query, name: []const u8) ?u32 {
    const n = q.captureCount();
    var i: u32 = 0;
    while (i < n) : (i += 1) {
        if (std.mem.eql(u8, q.captureNameForId(i) orelse "", name)) return i;
    }
    return null;
}

fn rangesTouchLine(ranges: []const ts.Range, line_start: usize, line_end: usize) bool {
    for (ranges) |r| {
        if (r.start_byte < line_end and r.end_byte > line_start) return true;
    }
    return false;
}

fn lessSpecificFirst(_: void, a: Highlighter.RawSpan, b: Highlighter.RawSpan) bool {
    return a.specificity > b.specificity;
}

fn colorEql(a: ?Color, b: ?Color) bool {
    if (a == null and b == null) return true;
    if (a == null or b == null) return false;
    const x = a.?;
    const y = b.?;
    return x.r == y.r and x.g == y.g and x.b == y.b and x.a == y.a;
}
