//! zoe's tree-sitter syntax highlighting: a registry that `dlopen`s
//! language parsers at runtime, and a `Highlighter` that keeps a parse
//! tree for the current buffer and turns it into per-line colour spans.
//!
//! **No grammar is compiled into zoe.** A "language" is a directory on
//! the grammar search path holding a `parser.so` -- a standalone
//! tree-sitter parser shared library exporting `tree_sitter_<name>` --
//! and a `highlights.scm` query. Adding a language is dropping such a
//! directory next to the others; see docs/decisions.md's zoe syntax
//! section. zoe links only libtree-sitter itself (the parse runtime and
//! the query engine) -- the grammars are data.
//!
//! **Highlighting is derived state, not editor state.** `editor.zig` /
//! `buffer.zig` stay pure and know nothing about this. `ui.zig` owns a
//! `Highlighter`, reparses the whole buffer when `Buffer.edits` moves,
//! and asks it for the spans of each visible line as it paints.
//!
//! Two deliberate v1 limitations, both documented in decisions.md:
//!   - Full reparse per edit, no incremental `Tree.edit`. Fast enough for
//!     the files zoe opens; the incremental path needs edit ranges out of
//!     `Buffer` and is deferred.
//!   - Only `highlights.scm` is consulted -- no `injections.scm` (so no
//!     embedded languages, e.g. code fences in Markdown) and no
//!     `locals.scm` (so no scope-aware local/parameter distinction).
//!   - Query predicates `#eq?` / `#not-eq?` / `#any-of?` / `#not-any-of?`
//!     are evaluated; a pattern carrying any other test predicate
//!     (`#match?`, `#lua-match?`, ...) is disabled wholesale rather than
//!     applied unconditionally, so we under-highlight instead of mis-
//!     highlighting.

const std = @import("std");
const ts = @import("tree_sitter");
const glyphwire = @import("glyphwire");
const buffer = @import("buffer.zig");

const Buffer = buffer.Buffer;
const Color = glyphwire.Color;

/// The oldest grammar ABI libtree-sitter here can parse. A `parser.so`
/// generated by a newer tree-sitter CLI than the runtime is rejected
/// with a clear message rather than crashing mid-parse.
pub const min_abi_version = ts.MIN_COMPATIBLE_LANGUAGE_VERSION;
pub const max_abi_version = ts.LANGUAGE_VERSION;

/// A run of one colour within a line, as byte offsets relative to the
/// line's first byte (its newline excluded). Non-overlapping and sorted
/// by `start`; a gap between spans means "the default text colour".
pub const Span = struct {
    start: usize,
    end: usize,
    color: Color,
};

/// Longest single line we bother to highlight. Past this the per-line
/// paint buffer is the dominant cost and a line that long is almost
/// always minified or generated anyway -- it renders in the plain
/// colour.
const max_highlight_line: usize = 1 << 15;

// ── Theme ───────────────────────────────────────────────────────────────

/// Maps a tree-sitter highlight capture name to a foreground colour.
///
/// Capture names are dotted and hierarchical (`string.special.key`); a
/// name with no colour of its own falls back to its prefix
/// (`string.special.key` -> `string.special` -> `string`). `null` for a
/// group means "don't colour it" -- the text keeps the pane's default.
pub const Theme = struct {
    colors: std.EnumArray(Group, ?Color),

    pub const Group = enum {
        comment,
        keyword,
        string,
        string_escape,
        string_special,
        escape,
        number,
        boolean,
        character,
        constant,
        constant_builtin,
        function,
        function_builtin,
        type,
        type_builtin,
        constructor,
        operator,
        property,
        variable,
        variable_builtin,
        variable_parameter,
        module,
        label,
        attribute,
        tag,
        punctuation,
        punctuation_special,
        text_title,
        text_literal,
        text_uri,
        text_reference,
    };

    /// The dotted capture names grammars actually emit, mapped to a
    /// group. `colorFor` walks a name down to its prefixes against this.
    const name_to_group = std.StaticStringMap(Group).initComptime(.{
        .{ "comment", .comment },
        .{ "keyword", .keyword },
        .{ "string", .string },
        .{ "string.escape", .string_escape },
        .{ "string.special", .string_special },
        .{ "escape", .escape },
        .{ "number", .number },
        .{ "float", .number },
        .{ "boolean", .boolean },
        .{ "character", .character },
        .{ "constant", .constant },
        .{ "constant.builtin", .constant_builtin },
        .{ "function", .function },
        .{ "function.builtin", .function_builtin },
        .{ "constructor", .constructor },
        .{ "type", .type },
        .{ "type.builtin", .type_builtin },
        .{ "operator", .operator },
        .{ "property", .property },
        .{ "field", .property },
        .{ "variable", .variable },
        .{ "variable.builtin", .variable_builtin },
        .{ "variable.parameter", .variable_parameter },
        .{ "variable.member", .property },
        .{ "parameter", .variable_parameter },
        .{ "module", .module },
        .{ "namespace", .module },
        .{ "import", .keyword },
        .{ "label", .label },
        .{ "attribute", .attribute },
        .{ "tag", .tag },
        .{ "punctuation", .punctuation },
        .{ "punctuation.special", .punctuation_special },
        .{ "text.title", .text_title },
        .{ "title", .text_title },
        .{ "text.literal", .text_literal },
        .{ "text.uri", .text_uri },
        .{ "text.reference", .text_reference },
    });

    fn rgb(hex: u24) Color {
        return .{
            .r = @intCast((hex >> 16) & 0xff),
            .g = @intCast((hex >> 8) & 0xff),
            .b = @intCast(hex & 0xff),
        };
    }

    /// A flat, dark palette in the spirit of the one in `ui.zig` --
    /// enough contrast between groups to read structure, nothing
    /// fluorescent. `variable` and `punctuation` are left uncoloured on
    /// purpose: colouring every identifier and bracket is noise.
    pub fn initDefault() Theme {
        var t = Theme{ .colors = std.EnumArray(Group, ?Color).initFill(null) };
        t.colors.set(.comment, rgb(0x5c6370));
        t.colors.set(.keyword, rgb(0xc678dd));
        t.colors.set(.string, rgb(0x98c379));
        t.colors.set(.string_escape, rgb(0x56b6c2));
        t.colors.set(.string_special, rgb(0x56b6c2));
        t.colors.set(.escape, rgb(0x56b6c2));
        t.colors.set(.number, rgb(0xd19a66));
        t.colors.set(.boolean, rgb(0xd19a66));
        t.colors.set(.character, rgb(0x98c379));
        t.colors.set(.constant, rgb(0xd19a66));
        t.colors.set(.constant_builtin, rgb(0xd19a66));
        t.colors.set(.function, rgb(0x61afef));
        t.colors.set(.function_builtin, rgb(0x61afef));
        t.colors.set(.type, rgb(0xe5c07b));
        t.colors.set(.type_builtin, rgb(0xe5c07b));
        t.colors.set(.constructor, rgb(0xe5c07b));
        t.colors.set(.operator, rgb(0x56b6c2));
        t.colors.set(.property, rgb(0xe06c75));
        t.colors.set(.variable_builtin, rgb(0xe06c75));
        t.colors.set(.variable_parameter, rgb(0xd19a66));
        t.colors.set(.module, rgb(0xe5c07b));
        t.colors.set(.label, rgb(0x61afef));
        t.colors.set(.attribute, rgb(0xd19a66));
        t.colors.set(.tag, rgb(0xe06c75));
        t.colors.set(.punctuation_special, rgb(0xc678dd));
        t.colors.set(.text_title, rgb(0x61afef));
        t.colors.set(.text_literal, rgb(0x98c379));
        t.colors.set(.text_uri, rgb(0x56b6c2));
        t.colors.set(.text_reference, rgb(0xe06c75));
        return t;
    }

    /// Override one group by its (undotted) name, e.g. `set("keyword",
    /// ...)`. An unknown name is ignored. Used by the Lua config.
    pub fn setByName(self: *Theme, name: []const u8, color: Color) bool {
        const g = name_to_group.get(name) orelse return false;
        self.colors.set(g, color);
        return true;
    }

    /// The colour for a capture name, or `null` for "leave it alone".
    pub fn colorFor(self: *const Theme, capture: []const u8) ?Color {
        var name = capture;
        while (true) {
            if (name_to_group.get(name)) |g| return self.colors.get(g);
            const dot = std.mem.lastIndexOfScalar(u8, name, '.') orelse return null;
            name = name[0..dot];
        }
    }
};

// ── Grammar registry ────────────────────────────────────────────────────

/// One `dlopen`ed grammar. The library and language pointer live for the
/// process -- tree-sitter language pointers must outlive every tree and
/// query built from them, and zoe only ever loads a grammar once, so it
/// is never closed.
pub const LoadedGrammar = struct {
    lib: std.DynLib,
    language: *const ts.Language,
    /// `highlights.scm` source, null-terminated, owned by the registry.
    highlights: [:0]u8,
};

/// Extension-to-grammar mapping, from the built-in defaults plus the Lua
/// config. `extensions` entries include the leading dot.
pub const LangDef = struct {
    name: []const u8,
    extensions: []const []const u8,
};

/// The six grammars `build.zig` compiles and installs. A config can add
/// more or remap these.
pub const default_langs = [_]LangDef{
    .{ .name = "zig", .extensions = &.{ ".zig", ".zon" } },
    .{ .name = "json", .extensions = &.{ ".json", ".jsonc" } },
    .{ .name = "c", .extensions = &.{ ".c", ".h" } },
    .{ .name = "python", .extensions = &.{ ".py", ".pyi" } },
    .{ .name = "toml", .extensions = &.{ ".toml" } },
    .{ .name = "markdown", .extensions = &.{ ".md", ".markdown" } },
};

/// The grammar directories to search, highest priority first:
///   1. `extra` (from `config.grammar_dirs`),
///   2. `$GLYPHWIRE_ZOE_GRAMMAR_DIR` (`:`-separated -- what `zig build`
///      points at the just-installed grammars),
///   3. `$XDG_CONFIG_HOME/glyphwire/zoe/grammars` (or `~/.config/...`),
///   4. `$XDG_DATA_HOME/glyphwire/grammars` (or `~/.local/share/...`),
///   5. `<exe dir>/../share/glyphwire/grammars` (an installed tree).
///
/// Every element is owned by `alloc`; free each, then the slice. Missing
/// env vars just drop their entry.
pub fn searchDirs(
    alloc: std.mem.Allocator,
    io: std.Io,
    environ: *const std.process.Environ.Map,
    extra: []const []const u8,
) ![]const []const u8 {
    var dirs: std.ArrayList([]const u8) = .empty;
    errdefer {
        for (dirs.items) |d| alloc.free(d);
        dirs.deinit(alloc);
    }

    for (extra) |d| try dirs.append(alloc, try alloc.dupe(u8, d));

    if (environ.get("GLYPHWIRE_ZOE_GRAMMAR_DIR")) |v| {
        var it = std.mem.tokenizeScalar(u8, v, ':');
        while (it.next()) |part| try dirs.append(alloc, try alloc.dupe(u8, part));
    }

    if (environ.get("XDG_CONFIG_HOME")) |xdg| {
        if (xdg.len > 0) try dirs.append(alloc, try std.fs.path.join(alloc, &.{ xdg, "glyphwire", "zoe", "grammars" }));
    } else if (environ.get("HOME")) |home| {
        try dirs.append(alloc, try std.fs.path.join(alloc, &.{ home, ".config", "glyphwire", "zoe", "grammars" }));
    }

    if (environ.get("XDG_DATA_HOME")) |xdg| {
        if (xdg.len > 0) try dirs.append(alloc, try std.fs.path.join(alloc, &.{ xdg, "glyphwire", "grammars" }));
    } else if (environ.get("HOME")) |home| {
        try dirs.append(alloc, try std.fs.path.join(alloc, &.{ home, ".local", "share", "glyphwire", "grammars" }));
    }

    if (std.process.executableDirPathAlloc(io, alloc)) |exe_dir| {
        defer alloc.free(exe_dir);
        try dirs.append(alloc, try std.fs.path.join(alloc, &.{ exe_dir, "..", "share", "glyphwire", "grammars" }));
    } else |_| {}

    return dirs.toOwnedSlice(alloc);
}

pub const Registry = struct {
    alloc: std.mem.Allocator,
    io: std.Io,
    /// Grammar directories, highest priority first. Owned.
    search_dirs: []const []const u8,
    /// Extension mapping, highest priority first (first match wins).
    /// Owned; strings borrowed from whatever built it (config arena or
    /// `default_langs`).
    langs: []const LangDef,
    /// name -> loaded grammar. Keys owned; values are boxed so the
    /// pointer `get` hands back stays valid across a later `get` that
    /// resizes the map.
    loaded: std.StringHashMapUnmanaged(*LoadedGrammar) = .empty,
    /// Names we tried and couldn't load, so a miss is logged once, not
    /// every keystroke. Keys owned.
    failed: std.StringHashMapUnmanaged(void) = .empty,

    pub fn init(
        alloc: std.mem.Allocator,
        io: std.Io,
        search_dirs: []const []const u8,
        langs: []const LangDef,
    ) Registry {
        return .{ .alloc = alloc, .io = io, .search_dirs = search_dirs, .langs = langs };
    }

    pub fn deinit(self: *Registry) void {
        var it = self.loaded.iterator();
        while (it.next()) |e| {
            self.alloc.free(e.value_ptr.*.highlights);
            // e.value_ptr.*.lib is intentionally not closed (see LoadedGrammar).
            self.alloc.destroy(e.value_ptr.*);
            self.alloc.free(e.key_ptr.*);
        }
        self.loaded.deinit(self.alloc);

        var fit = self.failed.keyIterator();
        while (fit.next()) |k| self.alloc.free(k.*);
        self.failed.deinit(self.alloc);
    }

    /// The grammar name for a file path, matched on its extension
    /// (case-insensitively). `null` when nothing maps.
    pub fn nameForPath(self: *const Registry, path: []const u8) ?[]const u8 {
        const ext = std.fs.path.extension(path);
        if (ext.len == 0) return null;
        for (self.langs) |l| {
            for (l.extensions) |e| {
                if (std.ascii.eqlIgnoreCase(e, ext)) return l.name;
            }
        }
        return null;
    }

    /// The loaded grammar for `name`, `dlopen`ing it on first use.
    /// `null` (logged once) when no directory on the search path has a
    /// usable `parser.so` + `highlights.scm` for it.
    pub fn get(self: *Registry, name: []const u8) ?*LoadedGrammar {
        if (self.loaded.get(name)) |g| return g;
        if (self.failed.contains(name)) return null;

        if (self.load(name)) |g| {
            var loaded = g;
            const box = self.alloc.create(LoadedGrammar) catch {
                self.alloc.free(loaded.highlights);
                loaded.lib.close();
                return null;
            };
            box.* = loaded;
            const key = self.alloc.dupe(u8, name) catch {
                self.alloc.free(box.highlights);
                box.lib.close();
                self.alloc.destroy(box);
                return null;
            };
            self.loaded.put(self.alloc, key, box) catch {
                self.alloc.free(key);
                self.alloc.free(box.highlights);
                box.lib.close();
                self.alloc.destroy(box);
                return null;
            };
            return box;
        } else |err| {
            std.log.warn("zoe: no usable '{s}' grammar on the search path ({t})", .{ name, err });
            const key = self.alloc.dupe(u8, name) catch return null;
            self.failed.put(self.alloc, key, {}) catch self.alloc.free(key);
            return null;
        }
    }

    const LoadError = error{ NotFound, BadAbi, OutOfMemory };

    fn load(self: *Registry, name: []const u8) LoadError!LoadedGrammar {
        const so_names = [_][]const u8{
            "parser.so",
            // `build.zig` installs the artifact under its own name.
            std.fmt.allocPrint(self.alloc, "libtree-sitter-{s}.so", .{name}) catch return error.OutOfMemory,
            std.fmt.allocPrint(self.alloc, "{s}.so", .{name}) catch return error.OutOfMemory,
        };
        defer self.alloc.free(so_names[1]);
        defer self.alloc.free(so_names[2]);

        const sym = symbolName(self.alloc, name) catch return error.OutOfMemory;
        defer self.alloc.free(sym);
        const LangFn = *const fn () callconv(.c) *const ts.Language;

        for (self.search_dirs) |dir| {
            for (so_names) |so| {
                const so_path = std.fs.path.join(self.alloc, &.{ dir, name, so }) catch return error.OutOfMemory;
                defer self.alloc.free(so_path);

                var lib = std.DynLib.open(so_path) catch continue;

                const lang_fn = lib.lookup(LangFn, sym) orelse {
                    lib.close();
                    continue;
                };
                const language = lang_fn();

                const abi = language.abiVersion();
                if (abi < ts.MIN_COMPATIBLE_LANGUAGE_VERSION or abi > ts.LANGUAGE_VERSION) {
                    std.log.warn(
                        "zoe: '{s}' grammar ABI {d} unsupported (need {d}..{d}); rebuild it",
                        .{ name, abi, ts.MIN_COMPATIBLE_LANGUAGE_VERSION, ts.LANGUAGE_VERSION },
                    );
                    lib.close();
                    return error.BadAbi;
                }

                const q_path = std.fs.path.join(self.alloc, &.{ dir, name, "highlights.scm" }) catch {
                    lib.close();
                    return error.OutOfMemory;
                };
                defer self.alloc.free(q_path);
                const scm = std.Io.Dir.cwd().readFileAllocOptions(
                    self.io,
                    q_path,
                    self.alloc,
                    .limited(4 * 1024 * 1024),
                    .of(u8),
                    0,
                ) catch {
                    lib.close();
                    continue;
                };

                return .{ .lib = lib, .language = language, .highlights = scm };
            }
        }
        return error.NotFound;
    }

    /// `tree_sitter_<name>`, with `-` turned into `_` the way the
    /// tree-sitter CLI does when it generates the entry point.
    fn symbolName(alloc: std.mem.Allocator, name: []const u8) ![:0]u8 {
        const sym = try std.fmt.allocPrintSentinel(alloc, "tree_sitter_{s}", .{name}, 0);
        for (sym) |*c| {
            if (c.* == '-') c.* = '_';
        }
        return sym;
    }
};

// ── Highlighter ─────────────────────────────────────────────────────────

const Predicate = struct {
    const Kind = enum { eq, not_eq, any_of, not_any_of };
    const Arg = union(enum) { capture: u32, text: []const u8 };

    kind: Kind,
    /// The capture the predicate constrains (its first `@arg`).
    capture: u32,
    args: []const Arg,
};

pub const Highlighter = struct {
    alloc: std.mem.Allocator,
    theme: Theme,
    parser: *ts.Parser,
    cursor: *ts.QueryCursor,

    /// The grammar name currently set, borrowed from the registry's key.
    lang_name: ?[]const u8 = null,
    query: ?*ts.Query = null,
    tree: ?*ts.Tree = null,
    /// The exact bytes `tree` was parsed from -- kept so `#eq?` /
    /// `#any-of?` can read a captured node's text. Owned.
    source: []u8 = &.{},

    /// capture id -> resolved colour (or null = don't colour). Rebuilt
    /// by `setLanguage`. Owned.
    capture_colors: []?Color = &.{},
    /// pattern index -> the predicates to check before applying its
    /// captures. A disabled pattern gets an empty slice. Owned (each
    /// inner `args` slice too).
    pattern_preds: []const []const Predicate = &.{},

    /// Per-line scratch: one entry per byte of the line, holding the
    /// winning colour so far. Reused across calls.
    paint: std.ArrayList(?Color) = .empty,
    raw: std.ArrayList(RawSpan) = .empty,

    const RawSpan = struct { start: usize, end: usize, specificity: u32, color: Color };

    pub fn init(alloc: std.mem.Allocator, theme: Theme) !Highlighter {
        const parser = ts.Parser.create();
        errdefer parser.destroy();
        const cursor = ts.QueryCursor.create();
        return .{ .alloc = alloc, .theme = theme, .parser = parser, .cursor = cursor };
    }

    pub fn deinit(self: *Highlighter) void {
        self.clearLanguage();
        self.cursor.destroy();
        self.parser.destroy();
        self.paint.deinit(self.alloc);
        self.raw.deinit(self.alloc);
        self.* = undefined;
    }

    /// A language has been chosen (its query compiled).
    pub fn languageSet(self: *const Highlighter) bool {
        return self.query != null;
    }

    /// A language is chosen *and* the current buffer has been parsed --
    /// `lineSpans` will do something.
    pub fn ready(self: *const Highlighter) bool {
        return self.query != null and self.tree != null;
    }

    pub fn clearLanguage(self: *Highlighter) void {
        if (self.tree) |t| {
            t.destroy();
            self.tree = null;
        }
        if (self.query) |q| {
            q.destroy();
            self.query = null;
        }
        self.parser.setLanguage(null) catch {};
        self.alloc.free(self.source);
        self.source = &.{};
        self.alloc.free(self.capture_colors);
        self.capture_colors = &.{};
        self.freePredicates();
        self.lang_name = null;
    }

    fn freePredicates(self: *Highlighter) void {
        for (self.pattern_preds) |preds| {
            for (preds) |p| self.alloc.free(p.args);
            self.alloc.free(preds);
        }
        self.alloc.free(self.pattern_preds);
        self.pattern_preds = &.{};
    }

    /// Switch to `grammar` (which outlives the Highlighter -- the
    /// registry owns it). Compiles the query and resolves its captures
    /// against the theme. On any failure the Highlighter is left with no
    /// language and the caller falls back to plain text.
    pub fn setLanguage(self: *Highlighter, name: []const u8, grammar: *const LoadedGrammar) !void {
        self.clearLanguage();

        self.parser.setLanguage(grammar.language) catch |e| {
            std.log.warn("zoe: parser rejected '{s}' grammar ({t})", .{ name, e });
            return error.IncompatibleGrammar;
        };

        var err_off: u32 = 0;
        const q = ts.Query.create(grammar.language, grammar.highlights, &err_off) catch |e| {
            std.log.warn("zoe: '{s}' highlights.scm rejected ({t}) at byte {d}", .{ name, e, err_off });
            self.parser.setLanguage(null) catch {};
            return error.BadQuery;
        };
        self.query = q;
        self.lang_name = name;

        try self.buildCaptureColors();
        try self.buildPredicates();
    }

    fn buildCaptureColors(self: *Highlighter) !void {
        const q = self.query.?;
        const n = q.captureCount();
        const colors = try self.alloc.alloc(?Color, n);
        var i: u32 = 0;
        while (i < n) : (i += 1) {
            colors[i] = self.theme.colorFor(q.captureNameForId(i) orelse "");
        }
        self.capture_colors = colors;
    }

    fn buildPredicates(self: *Highlighter) !void {
        const q = self.query.?;
        const pn = q.patternCount();
        const out = try self.alloc.alloc([]const Predicate, pn);
        errdefer self.alloc.free(out);

        var p: u32 = 0;
        while (p < pn) : (p += 1) {
            var list: std.ArrayList(Predicate) = .empty;
            errdefer {
                for (list.items) |it| self.alloc.free(it.args);
                list.deinit(self.alloc);
            }

            const steps = q.predicatesForPattern(p);
            var disable = false;
            var i: usize = 0;
            while (i < steps.len) {
                var j = i;
                while (j < steps.len and steps[j].type != .done) j += 1;
                const grp = steps[i..j];
                i = j + 1;
                if (grp.len == 0 or grp[0].type != .string) continue;

                const pname = q.stringValueForId(grp[0].value_id) orelse continue;
                const kind: Predicate.Kind = if (std.mem.eql(u8, pname, "eq?"))
                    .eq
                else if (std.mem.eql(u8, pname, "not-eq?"))
                    .not_eq
                else if (std.mem.eql(u8, pname, "any-of?"))
                    .any_of
                else if (std.mem.eql(u8, pname, "not-any-of?"))
                    .not_any_of
                else {
                    // A `!` step is a directive (`#set!`), harmless to
                    // ignore. Any other `?` test we can't evaluate, so
                    // the whole pattern is dropped rather than applied
                    // blind.
                    if (std.mem.endsWith(u8, pname, "?")) disable = true;
                    continue;
                };

                if (grp.len < 2 or grp[1].type != .capture) continue;
                var args: std.ArrayList(Predicate.Arg) = .empty;
                errdefer args.deinit(self.alloc);
                for (grp[2..]) |st| switch (st.type) {
                    .capture => try args.append(self.alloc, .{ .capture = st.value_id }),
                    .string => try args.append(self.alloc, .{ .text = q.stringValueForId(st.value_id) orelse "" }),
                    .done => {},
                };
                try list.append(self.alloc, .{
                    .kind = kind,
                    .capture = grp[1].value_id,
                    .args = try args.toOwnedSlice(self.alloc),
                });
            }

            if (disable) {
                q.disablePattern(p);
                for (list.items) |it| self.alloc.free(it.args);
                list.clearRetainingCapacity();
            }
            out[p] = try list.toOwnedSlice(self.alloc);
        }
        self.pattern_preds = out;
    }

    /// Reparse the whole buffer. Cheap enough per edit for zoe's file
    /// sizes; see the module note on the deferred incremental path.
    pub fn reparse(self: *Highlighter, buf: *const Buffer) !void {
        if (self.query == null) return;

        const src = try buf.text(self.alloc);
        errdefer self.alloc.free(src);

        const new_tree = self.parser.parseString(src, null) orelse return error.ParseFailed;

        if (self.tree) |t| t.destroy();
        self.tree = new_tree;
        self.alloc.free(self.source);
        self.source = src;
    }

    /// Fill `out` (cleared first) with the colour spans covering buffer
    /// byte range `[line_start, line_end)`, as offsets relative to
    /// `line_start`.
    pub fn lineSpans(self: *Highlighter, line_start: usize, line_end: usize, out: *std.ArrayList(Span)) !void {
        out.clearRetainingCapacity();
        const q = self.query orelse return;
        const tree = self.tree orelse return;
        const line_len = line_end -| line_start;
        if (line_len == 0 or line_len > max_highlight_line) return;

        self.raw.clearRetainingCapacity();
        self.cursor.setByteRange(@intCast(line_start), @intCast(line_end)) catch {};
        self.cursor.exec(q, tree.rootNode());

        while (self.cursor.nextMatch()) |m| {
            if (!self.predicatesOk(m)) continue;
            for (m.captures) |cap| {
                const color = self.capture_colors[cap.index] orelse continue;
                const s: usize = cap.node.startByte();
                const e: usize = cap.node.endByte();
                if (e <= line_start or s >= line_end) continue;
                const cs = if (s > line_start) s - line_start else 0;
                const ce = (if (e < line_end) e else line_end) - line_start;
                if (ce <= cs) continue;
                try self.raw.append(self.alloc, .{
                    .start = cs,
                    .end = ce,
                    .specificity = @intCast(e - s),
                    .color = color,
                });
            }
        }
        if (self.raw.items.len == 0) return;

        // Paint less-specific (wider) captures first so a nested, more-
        // specific capture wins the bytes it covers. Stable sort keeps
        // "a later match wins on a tie", matching tree-sitter's own
        // last-wins convention.
        std.sort.insertion(RawSpan, self.raw.items, {}, lessSpecificFirst);

        try self.paint.resize(self.alloc, line_len);
        @memset(self.paint.items, null);
        for (self.raw.items) |r| {
            @memset(self.paint.items[r.start..r.end], r.color);
        }

        var i: usize = 0;
        while (i < line_len) {
            const c = self.paint.items[i];
            var j = i + 1;
            while (j < line_len and colorEql(self.paint.items[j], c)) j += 1;
            if (c) |col| try out.append(self.alloc, .{ .start = i, .end = j, .color = col });
            i = j;
        }
    }

    fn predicatesOk(self: *Highlighter, m: ts.Query.Match) bool {
        const preds = self.pattern_preds[m.pattern_index];
        for (preds) |pr| {
            const lhs = self.captureText(m, pr.capture) orelse return false;
            switch (pr.kind) {
                .eq, .not_eq => {
                    if (pr.args.len == 0) continue;
                    const rhs = switch (pr.args[0]) {
                        .capture => |c| self.captureText(m, c) orelse return false,
                        .text => |t| t,
                    };
                    const equal = std.mem.eql(u8, lhs, rhs);
                    if ((pr.kind == .eq) != equal) return false;
                },
                .any_of, .not_any_of => {
                    var found = false;
                    for (pr.args) |a| {
                        const s = switch (a) {
                            .capture => |c| self.captureText(m, c) orelse continue,
                            .text => |t| t,
                        };
                        if (std.mem.eql(u8, lhs, s)) {
                            found = true;
                            break;
                        }
                    }
                    if ((pr.kind == .any_of) != found) return false;
                },
            }
        }
        return true;
    }

    fn captureText(self: *Highlighter, m: ts.Query.Match, capture_id: u32) ?[]const u8 {
        for (m.captures) |cap| {
            if (cap.index != capture_id) continue;
            const s: usize = cap.node.startByte();
            const e: usize = cap.node.endByte();
            if (e > self.source.len or s > e) return null;
            return self.source[s..e];
        }
        return null;
    }
};

fn lessSpecificFirst(_: void, a: Highlighter.RawSpan, b: Highlighter.RawSpan) bool {
    return a.specificity > b.specificity;
}

fn colorEql(a: ?Color, b: ?Color) bool {
    if (a == null and b == null) return true;
    if (a == null or b == null) return false;
    const x = a.?;
    const y = b.?;
    return x.r == y.r and x.g == y.g and x.b == y.b and x.a == y.a;
}
