-- zoe configuration template.
--
-- This is the full reference for `zoe.conf.lua`, the file zoe runs once at
-- startup (see zoe/langconf.zig `load`). Copy it to one of:
--
--   $GLYPHWIRE_CONFIG_DIR/zoe.conf.lua
--   $XDG_CONFIG_HOME/glyphwire/zoe.conf.lua
--   ~/.config/glyphwire/zoe.conf.lua                   (the usual location)
--
-- Every key is listed below at its built-in default, with every line
-- commented out -- so copying this file verbatim changes nothing.
-- Uncomment and edit only the keys you want to override. With no file at
-- all zoe highlights the bundled languages with its `default` dark theme,
-- embedded languages included.
--
-- Syntax: a plain Lua script (standard libraries open). Assign a single
-- global table named `config`. Unknown keys are ignored; a key of the
-- wrong type is logged and the default stands. Any parse error is logged
-- and whatever parsed before it is kept.
--
-- zoe.conf.lua carries syntax-highlighting, the colour theme and the
-- editor's display settings. Keybindings and the pane layout are not
-- configurable yet. gw-grep reads this file too, for the theme alone.

-- config = {
--
--     ---- Languages -------------------------------------------------
--
--     -- Extra languages, or extension overrides for the bundled ones.
--     -- Each entry maps a set of file extensions (leading dot included)
--     -- to a grammar directory name; zoe looks for
--     -- `<grammar_dir>/<name>/parser.so` plus `highlights.scm` on the
--     -- grammar search path (below). Config entries are matched before
--     -- the built-ins, so an entry may re-claim an extension a bundled
--     -- language already owns.
--     --
--     -- Bundled grammar names and their default extensions:
--     --   zig               .zig .zon
--     --   json              .json .jsonc
--     --   c                 .c .h
--     --   python            .py .pyi
--     --   toml              .toml
--     --   lua               .lua
--     --   bash              .sh .bash .zsh
--     --   markdown          .md .markdown
--     --   markdown_inline   (used via injections, no extensions)
--     languages = {
--         -- { name = "c",    extensions = { ".c", ".h", ".ino" } },
--         -- { name = "toml", extensions = { ".toml", ".conf" } },
--     },
--
--     ---- Grammar search path -------------------------------------
--
--     -- Extra directories to look in for grammar dirs, highest priority
--     -- first. `~` is expanded. These are prepended to zoe's built-in
--     -- search order:
--     --   1. config.grammar_dirs (this key)
--     --   2. $GLYPHWIRE_ZOE_GRAMMAR_DIR   (":"-separated; `zig build`
--     --      points this at the just-installed grammars)
--     --   3. $XDG_CONFIG_HOME/glyphwire/zoe/grammars
--     --        (or ~/.config/glyphwire/zoe/grammars)
--     --   4. $XDG_DATA_HOME/glyphwire/grammars
--     --        (or ~/.local/share/glyphwire/grammars)
--     --   5. <exe dir>/../share/glyphwire/grammars   (an installed tree)
--     -- A grammar dir is `<dir>/<name>/` holding `parser.so` (exporting
--     -- `tree_sitter_<name>`) and `highlights.scm`; adding a language
--     -- needs no rebuild.
--     grammar_dirs = {
--         -- "~/src/tree-sitter-grammars",
--     },
--
--     ---- Embedded languages -------------------------------------
--
--     -- Run `injections.scm` so embedded languages are highlighted too:
--     -- fenced code blocks in Markdown, Markdown inline markup, HTML
--     -- blocks. On by default; set false to turn it off.
--     injections = true,
--
--     ---- Editor ---------------------------------------------------
--
--     -- Lines a PageDown / PageUp (or Ctrl-D / Ctrl-U in normal mode)
--     -- moves the cursor. A number >= 1 replaces the default; anything
--     -- else is ignored.
--     page_lines = 10,
--
--     -- Rows a PageDown / PageUp moves the cursor in the file tree.
--     -- Left out (or zero), a page is the sidebar's own height less one
--     -- row of overlap, so it follows a resized pane on its own; a
--     -- number >= 1 pins it to that many rows instead. Separate from
--     -- `page_lines` because a page through a listing and a page through
--     -- text are not the same distance.
--     tree_page_lines = 0,
--
--     -- Typematic key repeat, in milliseconds: how long a key is held
--     -- before it starts repeating, then how often it repeats. zoe asks
--     -- glyphwire-host for these while it is focused, so they apply to
--     -- the editor without changing what the shell does. The host
--     -- clamps the delay to 0..5000 and the interval to 10..2000.
--     --
--     -- Normal and visual mode, where every repeat is a motion (`j`, an
--     -- arrow, PageDown). Much shorter than a terminal's hold, so a held
--     -- key starts moving quickly.
--     key_repeat_delay_ms = 300,
--     key_repeat_interval_ms = 30,
--
--     -- Insert and command mode, where a held key *types*. Same numbers
--     -- by default, and a separate setting so they can be pulled apart.
--     -- Careful dropping either delay much below this: an ordinary
--     -- keystroke is held for ~100ms, and a hold shorter than that turns
--     -- each one into several characters.
--     key_repeat_insert_delay_ms = 300,
--     key_repeat_insert_interval_ms = 30,
--
--     -- The buffer-pane line-number gutter:
--     --   false        -- no gutter
--     --   true         -- same as "absolute"
--     --   "absolute"   -- every line numbered from 1
--     --   "relative"   -- distance from the cursor, cursor line still absolute
--     -- `:set lineno=off|absolute|relative` changes it live.
--     line_numbers = "absolute",
--
--     -- Cells between tab stops: how wide a tab already in the file
--     -- renders, and the grid the Tab key indents onto. 1..16.
--     -- `:set tabwidth=N` changes it live.
--     tab_width = 4,
--
--     -- Whether the Tab key inserts spaces out to the next stop rather
--     -- than a literal tab character. `:set expandtab=on|off` changes it
--     -- live.
--     expand_tab = true,
--
--     -- Mark whitespace in the buffer pane: a faint middle dot on each
--     -- space, a faint arrow on the first cell of each tab. The rest of
--     -- a tab's run stays blank, so four spaces and one tab still read
--     -- differently. `:set whitespace=on|off` changes it live.
--     show_whitespace = false,
--
--     -- Milliseconds the pointer rests on a tab before the file's full
--     -- path pops up under it. 0 shows it at once.
--     tab_tooltip_delay_ms = 400,
--
--     ---- Language servers (LSP) ---------------------------------------
--
--     -- zoe talks to language servers for diagnostics, hover (K) and
--     -- goto-definition (gd). Each server below starts only if its binary
--     -- is on $PATH, so listing all of them costs nothing on a machine
--     -- that has none of them. `:lsp` says which are attached and which
--     -- were looked for and not found; `:lsp restart` brings back one
--     -- that crashed.
--     --
--     -- The built-in servers, at their defaults:
--     --   zls           zig      `zls`
--     --   basedpyright  python   `basedpyright-langserver --stdio`
--     --   ruff          python   `ruff server`
--     --
--     -- Two servers on Python is deliberate, and is the standard setup:
--     -- basedpyright for types, hover and navigation, ruff for lint and
--     -- formatting diagnostics. Diagnostics are kept per server, so
--     -- neither erases the other's, and each message is shown with the
--     -- name of the tool that reported it.
--     lsp = {
--         -- Master switch. false stops every server from starting.
--         enabled = true,
--
--         -- Merged with the built-ins **by name**: an entry naming one of
--         -- them overrides just the fields it mentions, and a new name
--         -- adds a server (which then needs both `cmd` and `languages`).
--         servers = {
--             -- A different binary, or one not on $PATH:
--             -- { name = "zls", cmd = { "/opt/zls/zls" } },
--
--             -- Turn a built-in off without restating the others:
--             -- { name = "ruff", enabled = false },
--
--             -- Add one. `languages` are grammar names -- the same ones
--             -- `languages` above uses -- not file extensions.
--             -- { name = "ty", languages = { "python" }, cmd = { "ty", "server" } },
--
--             -- `settings` is passed through verbatim as that server's
--             -- `initializationOptions`, so its shape is whatever the
--             -- server documents:
--             -- {
--             --     name = "basedpyright",
--             --     settings = {
--             --         python = { analysis = { typeCheckingMode = "standard" } },
--             --     },
--             -- },
--         },
--     },
--
--     ---- Theme --------------------------------------------------------
--
--     -- The colour theme: the syntax colours *and* everything else zoe
--     -- paints (panes, bars, tabs, cursor, selection, search matches,
--     -- diagnostics, popups). `:theme <name>` switches at runtime and
--     -- `:theme` alone names the current one. gw-grep reads this key
--     -- (and `themes`) from this file so its results match the editor.
--     --
--     -- A name picks a built-in or one of `themes` below:
--     --
--     --   default              zoe's own dark palette (One Dark syntax)
--     --   one-dark             Atom One Dark
--     --   vscode-light         VS Code Light+
--     --   github-dark          GitHub Dark Default
--     --   github-light         GitHub Light Default
--     --   catppuccin-mocha     catppuccin-macchiato   catppuccin-frappe
--     --   catppuccin-latte     (light)
--     --   tokyo-night
--     --   solarized-dark       solarized-light
--     --   darcula              JetBrains Darcula
--     --   cobalt2              Wes Bos's Cobalt2
--     --   dracula   nord   gruvbox-dark   monokai
--     --
--     -- An unknown name is logged and `default` is used.
--     theme = "default",
--
--     -- Or a table, a theme of its own (`:theme config` gets back to it):
--     --
--     --   theme = {
--     --       base = "github-dark",     -- start from this theme
--     --                                 -- (default: "default")
--     --       dark = true,              -- light or dark; picks the popup
--     --                                 -- frame, flips derived blends
--     --       panel_style = "panel",    -- popup nine-patch: "panel",
--     --                                 -- "panel_light", or your own
--     --                                 -- ~/.config/glyphwire/ninepatch/
--     --                                 -- <name>.9.png
--     --
--     --       -- The 15 colours every other one is derived from. Changing
--     --       -- one re-derives what is blended from it (bg -> tree,
--     --       -- tab bar, match highlight...), except slots the base
--     --       -- theme sets by hand.
--     --       palette = {
--     --           bg = "#0d1117", bg_dark = "#010409", bg_hi = "#21262d",
--     --           fg = "#e6edf3", fg_dim = "#6e7681", comment = "#8b949e",
--     --           selection = "#1f3b5a", cursor = "#2f81f7",
--     --           red = "#f85149", orange = "#ffa657", yellow = "#d29922",
--     --           green = "#3fb950", cyan = "#39c5cf", blue = "#58a6ff",
--     --           purple = "#bc8cff",
--     --       },
--     --
--     --       -- Any single UI colour, applied last:
--     --       ui = {
--     --           bg_buffer = "#...", bg_tree, bg_status, bg_tab_bar,
--     --           bg_tab, bg_shell, fg_text, fg_dim, fg_dir, fg_hidden,
--     --           fg_hidden_dir, fg_status, fg_mode, fg_error,
--     --           fg_whitespace, bg_cursor, fg_cursor, bg_selected,
--     --           bg_match, bg_match_current, fg_match (gw-grep),
--     --           fg_diag_error, fg_diag_warning, fg_diag_info,
--     --           fg_diag_hint, bg_popup, fg_popup, bg_popup_code,
--     --           fg_popup_rule, fg_popup_border, bg_popup_selected,
--     --           fg_popup_label, fg_popup_kind, fg_popup_detail,
--     --           bg_finder_header, fg_finder_header,
--     --           bg_finder_selected, fg_finder_selected,
--     --       },
--     --
--     --       -- Every other key is a capture-group colour, applied last.
--     --       -- Names are tree-sitter highlight captures; a dotted
--     --       -- name falls back to its prefix when unset
--     --       -- ("string.special.key" -> "string.special" -> "string").
--     --       -- `variable` and `punctuation` are left uncoloured by
--     --       -- every built-in (colouring every identifier and bracket
--     --       -- is noise), but can be set here.
--     --       keyword = "#ff7b72",
--     --       ["string.escape"] = "#79c0ff",
--     --       -- comment, keyword, string, string.escape, string.special,
--     --       -- escape, number, boolean, character, constant,
--     --       -- constant.builtin, function, function.builtin, type,
--     --       -- type.builtin, constructor, operator, property, variable,
--     --       -- variable.builtin, variable.parameter, module, label,
--     --       -- attribute, tag, punctuation, punctuation.special,
--     --       -- text.title, text.literal, text.uri, text.reference
--     --   }
--
--     -- Named themes of your own, in the table shape above, for `theme`
--     -- and `:theme` to pick. One named like a built-in replaces it;
--     -- `base` naming itself starts from the built-in of that name.
--     themes = {
--         -- mine = { base = "nord", palette = { bg = "#262a33" } },
--     },
-- }
