-- zoe configuration template.
--
-- This is the full reference for `zoe.conf.lua`, the file zoe runs once at
-- startup (see zoe/langconf.zig `load`). Copy it to one of:
--
--   $GLYPHWIRE_CONFIG_DIR/zoe.conf.lua
--   $XDG_CONFIG_HOME/glyphwire/zoe.conf.lua
--   ~/.config/glyphwire/zoe.conf.lua                   (the usual location)
--
-- Every key is listed below at its built-in default, with every line
-- commented out -- so copying this file verbatim changes nothing.
-- Uncomment and edit only the keys you want to override. With no file at
-- all zoe highlights the bundled languages in the window's theme
-- (theme.lua), embedded languages included.
--
-- Syntax: a plain Lua script (standard libraries open). Assign a single
-- global table named `config`. Unknown keys are ignored; a key of the
-- wrong type is logged and the default stands. Any parse error is logged
-- and whatever parsed before it is kept.
--
-- zoe.conf.lua carries syntax-highlighting, the colour theme, the
-- editor's display settings and its key bindings. The pane layout is not
-- configurable yet.

-- config = {
--
--     ---- Languages -------------------------------------------------
--
--     -- Extra languages, or extension overrides for the bundled ones.
--     -- Each entry maps a set of file extensions (leading dot included)
--     -- to a grammar directory name; zoe looks for
--     -- `<grammar_dir>/<name>/parser.so` plus `highlights.scm` on the
--     -- grammar search path (below). Config entries are matched before
--     -- the built-ins, so an entry may re-claim an extension a bundled
--     -- language already owns.
--     --
--     -- Bundled grammar names and their default extensions:
--     --   zig               .zig .zon
--     --   json              .json .jsonc
--     --   c                 .c .h
--     --   python            .py .pyi
--     --   toml              .toml
--     --   lua               .lua
--     --   bash              .sh .bash .zsh
--     --   markdown          .md .markdown
--     --   markdown_inline   (used via injections, no extensions)
--     --
--     -- `comment` sets the line-comment marker Ctrl+/ toggles. The bundled
--     -- languages have one already (`//` for zig and c, `#` for python,
--     -- toml and bash, `--` for lua; none for json and markdown), and an
--     -- entry without `comment` keeps its language's.
--     languages = {
--         -- { name = "c",    extensions = { ".c", ".h", ".ino" } },
--         -- { name = "toml", extensions = { ".toml", ".conf" } },
--         -- { name = "bash", extensions = { ".envrc" }, comment = "#" },
--     },
--
--     ---- Grammar search path -------------------------------------
--
--     -- Extra directories to look in for grammar dirs, highest priority
--     -- first. `~` is expanded. These are prepended to zoe's built-in
--     -- search order:
--     --   1. config.grammar_dirs (this key)
--     --   2. $GLYPHWIRE_ZOE_GRAMMAR_DIR   (":"-separated; `zig build`
--     --      points this at the just-installed grammars)
--     --   3. $XDG_CONFIG_HOME/glyphwire/zoe/grammars
--     --        (or ~/.config/glyphwire/zoe/grammars)
--     --   4. $XDG_DATA_HOME/glyphwire/grammars
--     --        (or ~/.local/share/glyphwire/grammars)
--     --   5. <exe dir>/../share/glyphwire/grammars   (an installed tree)
--     -- A grammar dir is `<dir>/<name>/` holding `parser.so` (exporting
--     -- `tree_sitter_<name>`) and `highlights.scm`; adding a language
--     -- needs no rebuild.
--     grammar_dirs = {
--         -- "~/src/tree-sitter-grammars",
--     },
--
--     ---- Embedded languages -------------------------------------
--
--     -- Run `injections.scm` so embedded languages are highlighted too:
--     -- fenced code blocks in Markdown, Markdown inline markup, HTML
--     -- blocks. On by default; set false to turn it off.
--     injections = true,
--
--     ---- Editor ---------------------------------------------------
--
--     -- Lines a PageDown / PageUp (or Ctrl-D / Ctrl-U in normal mode)
--     -- moves the cursor. A number >= 1 replaces the default; anything
--     -- else is ignored.
--     page_lines = 10,
--
--     -- Rows a PageDown / PageUp moves the cursor in the file tree.
--     -- Left out (or zero), a page is the sidebar's own height less one
--     -- row of overlap, so it follows a resized pane on its own; a
--     -- number >= 1 pins it to that many rows instead. Separate from
--     -- `page_lines` because a page through a listing and a page through
--     -- text are not the same distance.
--     tree_page_lines = 0,
--
--     -- Typematic key repeat, in milliseconds: how long a key is held
--     -- before it starts repeating, then how often it repeats. zoe asks
--     -- glyphwire-host for these while it is focused, so they apply to
--     -- the editor without changing what the shell does. The host
--     -- clamps the delay to 0..5000 and the interval to 10..2000.
--     --
--     -- Normal and visual mode, where every repeat is a motion (`j`, an
--     -- arrow, PageDown). Much shorter than a terminal's hold, so a held
--     -- key starts moving quickly.
--     key_repeat_delay_ms = 300,
--     key_repeat_interval_ms = 30,
--
--     -- Insert and command mode, where a held key *types*. Same numbers
--     -- by default, and a separate setting so they can be pulled apart.
--     -- Careful dropping either delay much below this: an ordinary
--     -- keystroke is held for ~100ms, and a hold shorter than that turns
--     -- each one into several characters.
--     key_repeat_insert_delay_ms = 300,
--     key_repeat_insert_interval_ms = 30,
--
--     -- The buffer-pane line-number gutter:
--     --   false        -- no gutter
--     --   true         -- same as "absolute"
--     --   "absolute"   -- every line numbered from 1
--     --   "relative"   -- distance from the cursor, cursor line still absolute
--     -- `:set lineno=off|absolute|relative` changes it live.
--     line_numbers = "absolute",
--
--     -- Cells between tab stops: how wide a tab already in the file
--     -- renders, and the grid the Tab key indents onto. 1..16.
--     -- `:set tabwidth=N` changes it live.
--     tab_width = 4,
--
--     -- Whether the Tab key inserts spaces out to the next stop rather
--     -- than a literal tab character. `:set expandtab=on|off` changes it
--     -- live.
--     expand_tab = true,
--
--     -- Mark whitespace in the buffer pane: a faint middle dot on each
--     -- space, a faint arrow on the first cell of each tab. The rest of
--     -- a tab's run stays blank, so four spaces and one tab still read
--     -- differently. `:set whitespace=on|off` changes it live.
--     show_whitespace = false,
--
--     -- Milliseconds the pointer rests on a tab before the file's full
--     -- path pops up under it. 0 shows it at once.
--     tab_tooltip_delay_ms = 400,
--
--     ---- Language servers (LSP) ---------------------------------------
--
--     -- zoe talks to language servers for diagnostics, hover (K) and
--     -- goto-definition (gd). Each server below starts only if its binary
--     -- is on $PATH, so listing all of them costs nothing on a machine
--     -- that has none of them. `:lsp` says which are attached and which
--     -- were looked for and not found; `:lsp restart` brings back one
--     -- that crashed.
--     --
--     -- The built-in servers, at their defaults:
--     --   zls           zig      `zls`
--     --   basedpyright  python   `basedpyright-langserver --stdio`
--     --   ruff          python   `ruff server`
--     --
--     -- Two servers on Python is deliberate, and is the standard setup:
--     -- basedpyright for types, hover and navigation, ruff for lint and
--     -- formatting diagnostics. Diagnostics are kept per server, so
--     -- neither erases the other's, and each message is shown with the
--     -- name of the tool that reported it.
--     lsp = {
--         -- Master switch. false stops every server from starting.
--         enabled = true,
--
--         -- Merged with the built-ins **by name**: an entry naming one of
--         -- them overrides just the fields it mentions, and a new name
--         -- adds a server (which then needs both `cmd` and `languages`).
--         servers = {
--             -- A different binary, or one not on $PATH:
--             -- { name = "zls", cmd = { "/opt/zls/zls" } },
--
--             -- Turn a built-in off without restating the others:
--             -- { name = "ruff", enabled = false },
--
--             -- Add one. `languages` are grammar names -- the same ones
--             -- `languages` above uses -- not file extensions.
--             -- { name = "ty", languages = { "python" }, cmd = { "ty", "server" } },
--
--             -- `settings` is passed through verbatim as that server's
--             -- `initializationOptions`, so its shape is whatever the
--             -- server documents:
--             -- {
--             --     name = "basedpyright",
--             --     settings = {
--             --         python = { analysis = { typeCheckingMode = "standard" } },
--             --     },
--             -- },
--         },
--     },
--
--     ---- Theme --------------------------------------------------------
--
--     -- zoe's own theme, overriding the window's (theme.lua) for the
--     -- editor alone. Absent, zoe follows the window's theme. A name or a
--     -- table, in exactly the shapes theme.lua takes -- see
--     -- host/theme.template.lua for the built-ins, the table keys and
--     -- every role -- and it may name a theme theme.lua defines.
--     -- `:theme <name>` switches at runtime, `:theme window` goes back to
--     -- the window's, and `:theme` alone names the current one.
--     theme = nil,
--
--     -- Named themes for `theme` and `:theme`, as in theme.lua.
--     themes = {
--         -- mine = { base = "nord", palette = { bg = "#262a33" } },
--     },
--
--     ---- Keys ---------------------------------------------------------
--
--     -- Rebind any chord or named key by action name, or set one to
--     -- `false` to take it away. Four tables: a key is looked up in the
--     -- editor mode's table first (`normal`, `visual`, `insert`; a
--     -- Shift+arrow selection made in insert mode reads `insert`), then
--     -- in `global`, so `false` in a mode table also hides the global
--     -- binding there. Entries go over the defaults; list only changes.
--     --
--     -- Chords are `mod+mod+key`: ctrl, alt, shift, super; keys are
--     -- glyphwire key names (`left`, `page_down`, `backspace`, `slash`,
--     -- `grave_accent`, `F5`) or the aliases `esc`, `del`, `pgdn`, `/`,
--     -- `-`, ... Modifiers must match exactly: `shift+tab` is not `tab`.
--     --
--     -- Unmodified letters in normal and visual mode (`dd`, `gg`) are
--     -- vim's grammar and not rebindable here, nor are Escape, the `:`
--     -- line's editing keys, the file tree's keys and the key after
--     -- Ctrl+W. docs/zoe-keys.md lists every action and its defaults.
--     keys = {
--         global = {
--             -- ["ctrl+h"] = false,
--             -- ["alt+h"]  = "toggleHidden",
--         },
--         normal = {},
--         visual = {},
--         insert = {
--             -- ["ctrl+d"] = "deleteWordForward",
--         },
--     },
-- }
