#!/usr/bin/env python3
# Copyright (c) 2026 Jeff DeWall
# SPDX-License-Identifier: MPL-2.0
"""Regenerates read/cjk_normalize_table.zig, the codepoint table behind
gw-read's CJK normalizations (`kana.normalize`).

Two of Yomitan's Japanese text preprocessors are just Unicode
normalization over a range, which Zig's std doesn't carry, so the
mappings are baked into a sorted table here:

  * CJK Compatibility (U+3300-33FF, squared words and units: ㍿, ㌀, ㎏)
    -> NFKC. Yomitan uses NFKD, which splits ㌀ into アハ゜ート with a
    combining mark that nothing recombines; NFKC gives アパート.
  * Radicals and strokes (KangXi U+2F00-2FDF, CJK Radicals Supplement
    U+2E80-2EFF, CJK Strokes U+31C0-31EF) -> NFKD where Unicode has a
    decomposition (all 214 KangXi radicals, 2 supplement radicals), else
    the Equivalent_Unified_Ideograph property. That second source goes
    beyond Yomitan: NFKD leaves ⺼ (U+2EBC) alone, and OCR emits
    supplement radicals as readily as KangXi ones. ⺼ -> 肉.

Usage: scripts/gen-cjk-normalize.py [EquivalentUnifiedIdeograph.txt]
(fetched from unicode.org when no path is given)
"""

import sys
import unicodedata
import urllib.request
from pathlib import Path

EUI_URL = "https://www.unicode.org/Public/UCD/latest/ucd/EquivalentUnifiedIdeograph.txt"
OUT = Path(__file__).resolve().parent.parent / "read" / "cjk_normalize_table.zig"

COMPAT = range(0x3300, 0x3400)
RADICALS = [range(0x2E80, 0x2F00), range(0x2F00, 0x2FE0), range(0x31C0, 0x31F0)]


def load_eui(text):
    """Equivalent_Unified_Ideograph: codepoint -> unified ideograph."""
    out = {}
    version = "?"
    for line in text.splitlines():
        if line.startswith("# EquivalentUnifiedIdeograph-"):
            version = line.split("-", 1)[1].removesuffix(".txt")
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        src, dst = (f.strip() for f in line.split(";"))
        lo, _, hi = src.partition("..")
        for cp in range(int(lo, 16), int(hi or lo, 16) + 1):
            out[cp] = int(dst, 16)
    return out, version


def zig_char(c):
    # Literal where it reads (ideographs, kana, letters), escaped where it
    # wouldn't (quotes, controls, combining marks).
    if c in '"\\' or unicodedata.category(c)[0] in "CMZ":
        return f"\\u{{{ord(c):x}}}"
    return c


def zig_string(s):
    return '"' + "".join(zig_char(c) for c in s) + '"'


def main():
    if len(sys.argv) > 1:
        eui_text = Path(sys.argv[1]).read_text(encoding="utf-8")
    else:
        with urllib.request.urlopen(EUI_URL) as resp:
            eui_text = resp.read().decode("utf-8")
    eui, eui_version = load_eui(eui_text)

    table = {}
    for cp in COMPAT:
        to = unicodedata.normalize("NFKC", chr(cp))
        if to != chr(cp):
            table[cp] = to
    for block in RADICALS:
        for cp in block:
            to = unicodedata.normalize("NFKD", chr(cp))
            if to == chr(cp) and cp in eui:
                to = chr(eui[cp])
            if to != chr(cp):
                table[cp] = to

    lines = [
        "// Copyright (c) 2026 Jeff DeWall",
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "",
        "// Generated by scripts/gen-cjk-normalize.py -- do not edit by hand.",
        f"// Unicode {unicodedata.unidata_version} (NFKC/NFKD), EquivalentUnifiedIdeograph {eui_version}.",
        "",
        "pub const Entry = struct { from: u21, to: []const u8 };",
        "",
        "/// Sorted by `from`, for binary search.",
        "pub const entries = [_]Entry{",
    ]
    for cp in sorted(table):
        lines.append(f"    .{{ .from = 0x{cp:X}, .to = {zig_string(table[cp])} }},")
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(table)} entries to {OUT}")


if __name__ == "__main__":
    main()
