-- gw-read configuration template.
--
-- This is the full reference for `read.conf.lua`, the file gw-read runs
-- once at startup (see read/config.zig `load`). Copy it to one of:
--
--   $GLYPHWIRE_CONFIG_DIR/read.conf.lua
--   $XDG_CONFIG_HOME/glyphwire/read.conf.lua
--   ~/.config/glyphwire/read.conf.lua                  (the usual location)
--
-- Every key is listed below at its built-in default, with every line
-- commented out -- so copying this file verbatim changes nothing.
-- Uncomment and edit only the keys you want to override.
--
-- Syntax: a plain Lua script (standard libraries open). Assign a single
-- global table named `config`. Unknown keys are ignored; a key of the
-- wrong type is logged and the default stands. Any parse error is logged
-- and whatever parsed before it is kept.
--
-- Note that a per-book reading position, sizing mode and direction are
-- remembered separately in `read.state.json` next to this file, and take
-- precedence over `mode` / `direction` here for a book you have opened
-- before. `--mode` / `--direction` on the command line beat both.

-- config = {
--
--     ---- Reading ---------------------------------------------------
--
--     -- Which way a page turn goes for a book you haven't opened
--     -- before. "rtl" is manga order: Left is *forward*, and a fresh
--     -- page starts at its right edge. "ltr" is western comic order.
--     -- `d` flips it at runtime.
--     direction = "rtl",
--
--     -- How the page is sized against the window on open:
--     --   "fit"         whole page visible          (`f`)
--     --   "fit-width"   page width fills the window (`w`)
--     --   "fit-height"  page height fills it        (`t`)
--     --   "natural"     one image pixel per screen pixel (`1`)
--     mode = "fit",
--
--     -- Whether a fit mode may scale a page *up* past its natural size.
--     -- Off leaves a small scan small in a large window.
--     upscale = true,
--
--     -- How many pages `]` and `[` jump by.
--     jump_pages = 5,
--
--     -- Remember where you left off in each book. Off opens everything
--     -- at page 1 and stops writing `read.state.json` entirely.
--     remember_position = true,
--
--     ---- Memory ----------------------------------------------------
--
--     -- How many pages of decoded image stay resident, so paging back
--     -- is instant. Each costs the page's own decoded size on the
--     -- glyphwire-host side; 8 is a few tens of MB for typical scans.
--     -- Range 1..64.
--     cache_pages = 8,
--
--     -- How many pages ahead (in reading order) to load before they are
--     -- asked for, hiding the read behind the page turn. Range 0..8;
--     -- `cache_pages` is raised to `prefetch + 2` if it is below it.
--     prefetch = 1,
--
--     ---- Zoom and pan ----------------------------------------------
--
--     -- Ceiling on the zoom factor, fit modes included. Raising this
--     -- costs glyphwire-host memory *quadratically*: a zoomed page is
--     -- drawn onto a layer the size of the whole scaled image, so 8x
--     -- covers four times as many cells as 4x. Range 1..16.
--     max_zoom = 4.0,
--
--     -- Cells panned per arrow key / `hjkl` press when the page is
--     -- bigger than the window. Range 1..64.
--     pan_step = 3,
--
--     ---- mokuro OCR ------------------------------------------------
--
--     -- These only do anything for a volume that came with a mokuro
--     -- sidecar: a `<book>.mokuro` beside the book, or a `*.mokuro`
--     -- packed at the top level of the .cbz (or sitting directly
--     -- inside the directory being read). Without one the reader
--     -- behaves exactly as it did before the feature existed.
--
--     -- Read the sidecar at all. `false` ignores it entirely: no text
--     -- dialog, no region outlines, no `ocr` marker on the statusline.
--     ocr = true,
--
--     -- Whether every text region starts outlined on the page. Off by
--     -- default -- the outlines are a "where can I click" hint, and a
--     -- page covered in them is not what a reader is for. `o` toggles
--     -- it at runtime; the bubble being read is always outlined.
--     ocr_hints = false,
--
--     -- The dialog's opacity while the peek key (`z`) is held, 0..1.
--     -- The point is to read the artwork *through* the text: mokuro
--     -- drops furigana often, so checking the page itself is a normal
--     -- part of reading with this on. 0 is fully transparent; 1
--     -- disables the peek. (`\` hides the dialog outright instead.)
--     ocr_peek = 0.5,
--
--     -- Widest the text dialog gets, in cells. Japanese sets two cells
--     -- per character, so 40 is about 20 characters a line -- close to
--     -- a bubble's own column length, which is what makes the re-wrap
--     -- read naturally rather than as one long ribbon. The panel is
--     -- sized to its text, so this is a cap, not a fixed width.
--     -- Range 12..200.
--     ocr_dialog_cols = 40,
--
--     -- Path to an already-*unzipped* Yomitan-format dictionary
--     -- directory -- e.g. a Jitendex download
--     -- (https://jitendex.org/pages/downloads.html) extracted once by
--     -- hand -- for word lookup out of the OCR dialog: click a word in
--     -- the open dialog to see its entry. Point this at the directory
--     -- containing index.json / term_bank_*.json, not at the .zip
--     -- itself; unzipping it on every book opened would be real time to
--     -- pay more than once for a dictionary this size. The first time
--     -- gw-read opens this directory it builds `index.sqlite3` inside
--     -- it from the term banks, a one-time cost; every book after that
--     -- just queries the file directly. Delete `index.sqlite3` to force
--     -- a rebuild after replacing the dictionary's contents. Empty --
--     -- the default -- leaves the feature off, the same as having no
--     -- mokuro sidecar.
--     dictionary = "",
--
--     -- Starting size of the lookup panel's title (the looked-up term)
--     -- -- "1x" (normal, the default), "1.5x", "2x", or "3x", drawn larger via
--     -- the wire protocol's text-scale support. `s` cycles it for the
--     -- rest of the session once a book is open; this only picks where
--     -- a freshly opened book starts.
--     dictionary_title_scale = "1x",
--
--     -- Size of the OCR dialog's text: "1x" (default), "1.5x", "2x" or
--     -- "3x". `S` cycles it for the session. `ocr_dialog_cols` stays
--     -- the wrap width at 1x, so a scaled dialog shows the same
--     -- characters per line and grows wider (it wraps sooner only when
--     -- the window is too narrow).
--     ocr_text_scale = "1x",
--
--     -- AI translation of the whole OCR bubble: `a` (or the ` a:AI `
--     -- tag on the dialog's border) asks about the open bubble and
--     -- shows the answer where the dictionary panel goes. The bubble's
--     -- OCR text leaves this machine when this is on -- never images,
--     -- never the book's path -- so it is off until you turn it on.
--     ai_lookup = false,
--
--     -- Where the text goes:
--     --   "openai"      OpenAI's Responses API (API key, billed by OpenAI)
--     --   "anthropic"   Anthropic's Messages API (API key from
--     --                 console.anthropic.com, billed per token -- *not*
--     --                 covered by a Claude/Claude Code subscription)
--     --   "claude_code" runs the `claude` CLI headless (`claude -p`, no
--     --                 tools, no saved session) on your existing Claude
--     --                 Code login, so it counts against that plan's usage
--     --                 rather than needing API credits
--     --   "ollama"      a local Ollama's /api/chat (no key, nothing leaves
--     --                 the machine unless the endpoint is remote)
--     ai_provider = "openai",
--
--     -- Empty means the provider's default: "gpt-5" for openai,
--     -- "claude-opus-5" for anthropic and claude_code, "qwen2.5" for
--     -- ollama. claude_code also takes the CLI's aliases ("sonnet").
--     ai_model = "",
--
--     -- Empty means the provider's default: the API URL
--     -- (https://api.openai.com/v1/responses,
--     -- https://api.anthropic.com/v1/messages,
--     -- http://localhost:11434/api/chat), or for claude_code the
--     -- executable to run ("claude", looked up on PATH).
--     ai_endpoint = "",
--
--     -- The *name* of the environment variable holding the API key (not
--     -- the key), so this file can be shared. Empty means the provider's
--     -- own: OPENAI_API_KEY or ANTHROPIC_API_KEY. ollama and claude_code
--     -- don't use one.
--     ai_api_key_env = "",
--
--     -- Your reading level and the style you want, appended to gw-read's
--     -- fixed rules (plain short text, translation first, no tables, no
--     -- romanization). For example:
--     --   "Explain the highlighted word in context. Mention grammar only
--     --    if it changes the meaning."
--     ai_prompt = "Translate this for an intermediate (around JLPT N3) Japanese learner. Keep the explanations brief.",
--
--     -- Also send the bubbles before and after this one (reading order)
--     -- as context.
--     ai_include_neighbor_dialog = true,
--
--     -- Also send the book's file name (never its path) and the page
--     -- number.
--     ai_include_book_info = false,
--
--     -- Ask before the first send of each session, naming where the text
--     -- is going. Cached answers never ask.
--     ai_confirm_before_send = true,
--
--     -- Keep answers in read.ai-cache.sqlite3 in this directory, keyed by
--     -- the provider, model and exact text sent, so reopening a bubble is
--     -- instant and costs nothing. Delete the file to clear it.
--     ai_cache = true,
--
--     ---- Anki cards ------------------------------------------------
--
--     -- `c` with a dictionary lookup (or an AI answer) showing makes an
--     -- Anki card from it, jidoujisho-style: pick a crop of the page for
--     -- context (drag moves it, dragging an edge / Alt+drag resizes, +/-
--     -- size it, Enter keeps it, Esc means no image), check the preview,
--     -- Enter sends it. Needs desktop Anki running with the AnkiConnect
--     -- add-on (code 2055492159); Anki's own sync carries the card to
--     -- AnkiWeb. An AI answer with no word looked up makes a sentence
--     -- card: the bubble as the term, the translation as the meaning.
--     anki_cards = true,
--
--     -- Where AnkiConnect listens, and where the card goes.
--     anki_url = "http://127.0.0.1:8765",
--     anki_deck = "Default",
--     anki_model = "jidoujisho Kinomoto",
--
--     -- Which note field each piece of the card fills. Sources: term,
--     -- reading, furigana ("見張[みは]る"), sentence, cloze_before,
--     -- cloze_inside, cloze_after, meaning (dictionary senses), ai (the
--     -- AI explanation, when the bubble has one open or cached), book,
--     -- page, image, audio. A field mapped to false is left out. The
--     -- default is jidoujisho's own note type:
--     anki_fields = {
--         ["Term"] = "term",
--         ["Reading"] = "reading",
--         ["Furigana"] = "furigana",
--         ["Sentence"] = "sentence",
--         ["Cloze Before"] = "cloze_before",
--         ["Cloze Inside"] = "cloze_inside",
--         ["Cloze After"] = "cloze_after",
--         ["Meaning"] = "meaning",
--         ["Notes"] = "ai",
--         ["Context"] = "book",
--         ["Image"] = "image",
--         ["Term Audio"] = "audio",
--     },
--
--     -- Space-separated tags on every card.
--     anki_tags = "gw-read",
--
--     -- Let a card through when the deck already has a note with the
--     -- same first field. Off, Anki refuses it and the preview says so.
--     anki_allow_duplicates = false,
--
--     -- Ask Anki to sync to AnkiWeb after every card.
--     anki_sync_after_add = false,
--
--     -- The word's audio: {term} and {reading} are filled in. Empty turns
--     -- audio off. JapanesePod101's "no recording" placeholder is
--     -- detected and never attached.
--     anki_audio_url = "https://assets.languagepod101.com/dictionary/japanese/audiomp3.php?kanji={term}&kana={reading}",
--
--     -- The crop is scaled down (never up) to fit these, and saved as a
--     -- JPEG at this quality (1..100).
--     anki_image_max_width = 800,
--     anki_image_max_height = 800,
--     anki_image_quality = 85,
-- }
